[Team-19][BE][Hwi&Jun] - 1주차 2번째 PR 요청
codesquad-members-2022/airbnb pull request #111
Opened 2022-05-27 10:02 UTC by hwicode

안녕하세요 Jack, Hwi & Jun 입니다. 우선 바쁜 시간 내서 PR 주셔서 감사합니다.
프로젝트 초기라 질문이 많진 않지만 잘 부탁드립니다 :smile:

2시쯤에 PR을 보냈으나 깃 충돌이 발생해서 이를 해결하다가 늦었네요ㅠㅠㅠ
앞으로는 깃 충돌이 발생하지 않도록 팀원들과 대화를 나눠보겠습니다.

한 주가 마무리 되었는데  행복한 주말 보내시길 바랍니다 Jack~~!!ㅎㅎㅎ

<br/>

> 저번에 답해주신 `Wish`를 `List`로 받는 방법을 채택했습니다. 감사합니다 🙇‍♂️
# airbnb

####  🌱 [team 규칙](https://github.com/hwicode/airbnb/wiki/backend-QuestionContent)

<br>

####  🙂 [mock api 문서](https://documenter.getpostman.com/view/20411388/Uz59Nf4d#b825fc2e-7dc8-4492-a493-bd9160ac03ce)

<br>

<details>
<summary>📑 ERD 설계</summary>

<div markdown=“1”>

![airbnb](https://user-images.githubusercontent.com/92818747/170630909-d5e0758f-6089-47de-b6d1-39d6a42912ee.PNG)

</div>
</details>

<br>
<details>
<summary>❓ 질문 사항</summary>
<div markdown=“1">
<br>
검색조건이 많을 때 요청을 @Requestbody 에 담아서 보내는 것과 RequestParam으로 각각 보내는 것 중 어떤게 더 나은지 리뷰어님의 의견을 듣고싶습니다.
</div>
</details>

2022-05-29 05:32 UTC, guswns1659 requested changes
구현하시느라 수고하셨어요 👍 

프로젝트의 구조가 만들어지는게 눈에 보이네요 ㅎㅎ 

몇가지 질문 남겼고 편안하게 답변 남겨주세요! 
오후 10시에는 머지할게요 ~

2022-05-29 05:32 UTC, guswns1659 commented on Backend/build.gradle
> +    implementation "com.querydsl:querydsl-apt:${queryDslVersion}"
nit;

어떤건 괄호가 있고 어떤 건 없어서 implementation의 작성 컨벤션을 맞추는게 깔끔할 것 같네요 : )

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
> +    private Integer accommodationId;
nit; 

현 도메인에서는 Integer로도 충분해보이지만 실제 비즈니스에서는 Long을 주로 사용합니다 : ) 
비즈니스가 확장돼서 Integer로 감당이 안되는 상황이 꽤나 자주 발생하기에

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/member/Member.java
> +        return Role.NORMAL;
Role.HOST가 되어야 할 것 같습니다?

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
ask; 

1. FetchType.LAZY로 설정한 이유가 있을까요?? 
2. Cascade는 영속성을 전파하기 위해 사용되는데, 어떤 이유로 PERSIST 옵션을 추가하셨을까요?

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
> +                         int maxNumberOfPeople, City city) {
롬복 사용하시는 거면 @Builder 써도 좋겠네요 ㅎㅎ

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Address.java
> +    private String gu;
ask; 

gu가 어떤 의미인가요?

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Location.java
> +    private double longtitude;
nit; 

longitude

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Image.java
> +    void registAccommodation(Accommodation accommodation) {
ask; 

package private으로 접근제어자를 설정한 이유가 있을까요?

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/member/Bio.java
> +public enum Bio {
bio는 어떤 단어를 축약하신건가요? 
너무 길지 않으면 변수를 있는 그대로 풀어써도 좋을 것 같습니다.

2022-05-29 05:32 UTC, guswns1659 commented on Backend/src/main/resources/application.yml
> +        format_sql: true
profile이 하나인데 개발단계라 show_sql: true는 의도하신거죠? 
추후 배포할 때는 profile 별 설정이 구분되면 좋겠네요

2022-05-29 05:32 UTC, guswns1659 commented on Backend/build.gradle
> +    implementation "com.querydsl:querydsl-jpa:${queryDslVersion}"
queryDsl을 사용하시는군요 ㅎㅎ

2022-05-29 05:51 UTC, guswns1659 commented
> 검색조건이 많을 때 요청을 @requestbody 에 담아서 보내는 것과 RequestParam으로 각각 보내는 것 중 어떤게 더 나은지 리뷰어님의 의견을 듣고싶습니다.

저는 RequestBody 대신에 검색조건이 많으면 아래 첨부하는 방법 중 하나를 고민할 거 같네요. Map도 있고, POJO 객체로 바로 매핑시킬 수도 있어요 
[https://tedblob.com/spring-boot-bind-request-parameters-to-object/](https://tedblob.com/spring-boot-bind-request-parameters-to-object/)

param이 많아진다고 GET 메서드를 POST로 바꿀 필요는 없어보입니다 ; )

2022-05-29 15:30 UTC, devjun10 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
데이터는 필요한 시점에 @BatchSize나 페치조인, 전역 배치 사이즈로 관리하면 되지만 해당 엔티티가 저장/수정/삭제 등을 할때는 별도로 속성을 관리하기 위해 PERSIST를 주었습니다!

제가 잘못 알고 있을수도 있는데 FetchType.LAZY와 Cascade는 별도의 속성으로 알고 있습니다!  

- LAZY 로딩의 경우 데이터를 가져올때 어느 시점에 데이터를 채우는지
- Cascade는 하나의 엔티티를 저장/수정/삭제 등을 할때 해당 속성이 다른 엔티티로 전파

2022-05-29 15:31 UTC, devjun10 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Image.java
> +    void registAccommodation(Accommodation accommodation) {
실수한 것 같습니다. 수정하겠습니다!

2022-05-29 15:32 UTC, devjun10 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/member/Bio.java
> +public enum Bio {
성별을 나타내려고 했는데 GENDER나 다른 변수로 바꾸는게 더 나을 것 같습니다!

2022-05-29 15:45 UTC, hwicode commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Address.java
> +    private String gu;
도시지역면적은 "시도/시/군/구"가 존재하는 데 여기서 "구"를 의미합니다!

ex) 마포구, 용산구, 서초구, 영등포구

2022-05-29 20:49 UTC, merged

2022-05-30 10:43 UTC, guswns1659 commented on Backend/src/main/java/com/example/airbnb/business/core/domain/accommodation/Accommodation.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
@devjun10 
네네. 잘 알고 계십니다 ; )

다만, PERSIST는 삭제할 때는 전파가 안될꺼에요! REMOVE도 추가하거나 ALL을 사용하셔야 할 것 같아요. 
추가로 Cascade 사용 시 주의할 사항은 A의 영속성이 B한테 전파되기 때문에 B를 다른 객체가 알고 있는지 확인하는 것도 중요합니다. A가 삭제되면 B도 같이 삭제될 때 C라는 객체가 B를 알고 있다면 문제가 될 수 있겠죠. 
비즈니스 상황에 따라 다르지만 ; )

2022-05-30 10:44 UTC, guswns1659 commented
코멘트 확인했습니다 : ) 👍