[team-21] 데이먼 1주차 2번째 PR 요청
codesquad-members-2022/airbnb pull request #116
Opened 2022-05-27 12:13 UTC by dukcode

안녕하세요 Dan :smile: 1주차 2번째 PR 요청 드립니다!

이번 PR의 **작업내역**과 **고민점**은 다음과 같습니다

## 작업내역

### 빈 방 가격 그래프 제공 API 구현

다음 그림과 같이 요금 버튼을 누르면 **설정한 체크인, 체크아웃 기간 내에 예약이 없는 방들**의. 
**최소, 최대 가격**과 **가격 분포**를 제공해 주는 API를 구현했습니다.

![image](https://user-images.githubusercontent.com/59705184/170696192-1b79e0eb-cf90-49b0-9961-06b2d8c123bd.png)

## 고민한 내용

* 코드 첨부

2022-05-27 12:25 UTC, dukcode commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +    @GetMapping("/charge_distribution")
해당 API의 GetMapping을 `/rooms/charge_distribution` 으로 결정했습니다.

REST의

> 자원을 이름(자원의 표현)으로 구분하여 해당 자원의 상태(정보)를 주고 받는 모든 것을 의미한다.

에 기반해서 URL을 정했는데 `가격 분포`가 `room` 자체가 아니다 보니 `/room_charge_distribution` 같은 방법도 고민해 봤었는데 둘중에 어떤것이 더 적절한 설계일까요..?

2022-05-27 12:35 UTC, dukcode commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +            @RequestBody RoomChargeDistributionRequest roomChargeDistributionRequest) {
GET에 body를 실어 보내도 되는지 고민하다가

[HTTP GET 메소드와 body](https://brunch.co.kr/@kd4/158)의 글을 보고 URL을 깔끔함을 선택했습니다.

2022-05-27 13:07 UTC, dukcode commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    @Builder
저번 [PR comment](https://github.com/codesquad-members-2022/airbnb/pull/44#discussion_r882243802)에서 Builder 패턴에 대해 장단점을 고민해보라고 하셨습니다.  

## 질문1 - Test에만 필요한 코드

당시에는 프로젝트에 필요한 코드는 아니었지만 Test 코드를 짜기 위해 Builder를 넣었었는데요.  

**Dan은 프로젝트에는 필요 없지만 Test를 위해 필요한 코드가 있을 때 어떤 방식으로 해결 하시는지 궁금합니다!**

## 질문2 - Builder 패턴의 단점

### [기본생성자 + Setter의 사용]

- Setter의 존재로 Data 변경 추적이 어려워 불변객체를 지향하는것이 좋음(변경 필요 시, 의미있는 메서드 사용)

### [불변객체를 유지하기 위해 초기화에 생성자만을 사용]

- 초기화하지 않아도 되는 field가 있을 때, 생성자를 여려개 만들어야함. 또한 field가 많아질 경우 가독성 낮아짐

### [Builder 패턴]

- 위의 문제를 모두 해결, 하지만 내부 Builder클래스의 존재로 **코드가 장황**해짐

### [LomBok의 @Builder사용]
- 위의 문제를 모두 해결, [LINK](https://stackoverflow.com/questions/29885428/required-arguments-with-a-lombok-builder)의 내용으로 필수값 설정 가능  

따라서 단점 없음(?)으로 생각되는데 어떤 단점이 또 있을까요?

2022-05-27 13:35 UTC, dukcode commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    public int getDistributedRoomCharge(int distributionUnit) {
[이전 PR 리뷰](https://github.com/codesquad-members-2022/airbnb/pull/44#discussion_r882247568)를 보고 해당 계산에 대한 책임은 Room 클래스가 가지는게 맞는것 같아 리팩토링과 함께 Room내부 메서드로 변경하였습니다.

2022-05-27 13:38 UTC, dukcode commented on BE/src/main/java/team21/airbnb/dto/request/RoomChargeDistributionRequest.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
해당 NoArgsContructor는 역직렬화에 필수이므로 추가했습니다. 또한 해당 생성자가 프로젝트에서 필요하기 전까지는 AccessLevel을 PRIVATE으로 묶어두어 무분별하게 사용하지 못하도록 했습니다.

2022-05-27 13:39 UTC, dukcode commented on BE/src/main/java/team21/airbnb/dto/request/RoomChargeDistributionRequest.java
> +    public RoomChargeDistributionRequest(LocalDate checkInDate, LocalDate checkOutDate) {
해당 생성자도 프로젝트에서는 필요하지 않지만 테스트코드에서 필요하기에 추가했습니다.

2022-05-27 13:40 UTC, dukcode commented on BE/src/main/java/team21/airbnb/repository/BookingRepository.java
> +    private EntityManager em;
EntityManager의 DI에서 @Autowired와 @PersistenceContext 두가지 방법이 있는것으로 알고 있는데 Dan은 어떤 방법을 선호하는지 궁금합니다!

2022-05-27 13:40 UTC, dukcode commented on BE/src/main/java/team21/airbnb/repository/RoomRepository.java
> +    @PersistenceContext
EntityManager의 DI에서 @Autowired와 @PersistenceContext 두가지 방법이 있는것으로 알고 있는데 Dan은 어떤 방법을 선호하는지 궁금합니다!

2022-05-27 13:44 UTC, dukcode commented on BE/src/main/java/team21/airbnb/repository/RoomRepository.java
> +                        "select r from Room r where not exists"
checkInDate와 checkOutDate사이에 예약이 없는 Room을 가져오는 메서드 입니다.  

예약이 빈 방은 Booking이 존재하지 않으므로, 전체 Room중에서 체크인 체크아웃 기간에 Booking이 존재하는 Room만 제외하는 방식으로 쿼리를 짰습니다.

2022-05-27 13:47 UTC, dukcode commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +            graph.merge(room.getDistributedRoomCharge(DISTRIBUTION_UNIT), 1, Integer::sum);
room 클래스의 public 메서드로 집어넣었습니다.

2022-05-27 13:47 UTC, dukcode commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +    public static final int DISTRIBUTION_UNIT = 10;
[이전 PR 리뷰](https://github.com/codesquad-members-2022/airbnb/pull/44#discussion_r882245481)에서 의미를 알기 어렵기에 이름을 변경했습니다.  

ex) 11원, 13원, 21원 -> 10원대 2개, 20원대 2개

2022-05-27 13:50 UTC, dukcode commented on BE/src/test/java/team21/airbnb/controller/RoomControllerTest.java
> +    @MockBean
[이전 PR 리뷰](https://github.com/codesquad-members-2022/airbnb/pull/44#discussion_r882247249)에서 RestTemplate 대신 MockMvc를 사용해 Controller를 테스트 해보았습니다.

2022-05-27 13:53 UTC, dukcode commented on BE/src/test/java/team21/airbnb/controller/RoomControllerTest.java
> +                .willReturn(new RoomChargeDistributionResponse(MIN_ROOM_CHARGE, MAX_ROOM_CHARGE,
프로젝트 전체 Bean을 로드하지 않아서 조금 테스트가 가벼워진 느낌이긴 한데, 제 생각에는 위의 코드처럼 Mock 객체의 행동을 미리 지정해줘야 된다는 점에서 실수가 발생할 가능성이 있어보입니다.  

WebMvcTest는 가볍지만 Mock객체의 응답을 지정해줘야하는 부담감이 있고,  
RestTemplate는 무겁지만 Service가 구현되었다는 가정하에 조금 더 편한 방법이라고 생각되는데. 

해당 방법보다 더 좋은방법이 있는지 Dan의 생각이 궁금합니다.!

2022-05-27 16:52 UTC, Hyune-c requested changes
수고하셨습니다.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +@RequestMapping("/rooms")
`nit`
저는 RequestMapping을 클래스 레벨로 묶는 것을 선호하지 않습니다.
경험상 에러가 발생하면 url을 통해 엔드포인트로 바로 가고 싶은 니즈가 있는데, 이렇게 분리되면 복붙이 불편했습니다.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +    @GetMapping("/charge_distribution")
`가격 분포`라는 결과에 너무 집중되어 특화 API를 만드신 것 같습니다.
의도한 것이라면 괜찮지만 RESTful과는 거리가 있어보입니다.

- 이 API에서 기대하는 것은 `해당 날짜 범위의 숙박 업소 가격 분포` 입니다.
- 분포를 내기 위해 필요한 건 `숙박 업소별로 날짜 범위 가격 합` List 입니다. 

이러면 분포라는 단어를 뺄 수 있겠죠. 
좀 더 리소스 집중된 설계를 추천합니다.

---

네이버 급쯤 되면 통계 전용 API를 따로 제공하기도 합니다.
하지만 지금 공부하실 건 특화 API가 아닌 RESTful한 범용 API라고 생각합니다.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +            @RequestBody RoomChargeDistributionRequest roomChargeDistributionRequest) {
https://hyune.gitbook.io/hyune-wiki/computer-science/web/rest-api/get-payload

네. `GET 메서드에 payload를 사용하는 것이 가능한가?`에 대한 것은 동의되었습니다.
링크도 읽어봐주세요.

하지만 `지금의 구현에서 payload를 사용하는 것이 적합한가?` 는 동의되지 않습니다.

- 지금의 구현에서 payload를 사용함으로서 본 이득은 변수 2개를 1개로 만든 것 뿐입니다.
- 이게 보편적인 API 설계를 해칠만큼 큰 이득인가요?

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    @Builder
https://hyune.gitbook.io/hyune-wiki/computer-science/design-pattern/builder-pattern

참고해주세요.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    public int getDistributedRoomCharge(int distributionUnit) {
distributionUnit이 뭘까요? 분포 단위?

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/dto/request/RoomChargeDistributionRequest.java
> +    public RoomChargeDistributionRequest(LocalDate checkInDate, LocalDate checkOutDate) {
`nit` 이런건 lombok 활용이 좋다고 생각해요.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/repository/RoomRepository.java
> +    @PersistenceContext
https://www.inflearn.com/questions/152202
https://stackoverflow.com/questions/31335211/autowired-vs-persistencecontext-for-entitymanager-bean/58891587#58891587

어.. 솔직히 저는 EntityManager를 실무 코드에서 써본 적이 없어요.
테스트 코드에서는 가끔 조작하기 위해 써보긴 했습니다.
왜냐하면 이렇게 네이티브 쿼리를 쓸 일이 없고, querydsl이나 jooq를 활용했기 때문이죠.

그래서 제 사용 의견은 드릴 수가 없을 것 같고, 관련 링크를 참고해주세요.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/repository/RoomRepository.java
> +                        "select r from Room r where not exists"
`nit`repository를 보니 네이티브 쿼리만 존재하는 것 같은데 `@Query`를 활용해보는 것은 어떤가요?

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +            RoomChargeDistributionRequest roomChargeDistributionRequest) {
`nit`
```suggestion
    public RoomChargeDistributionResponse getRoomChargeDistribution(
            RoomChargeDistributionRequest request) {
```

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +            graph.merge(room.getDistributedRoomCharge(DISTRIBUTION_UNIT), 1, Integer::sum);
`nit`
- 도메인 로직이라고 판단되시는 거면 `DISTRIBUTION_UNIT`이 room으로 가는 것이 낫지 않을까요?
- 저라면 이런 단순 계산식은 Math를 활용하거나 유틸 클래스를 만들 것 같긴 합니다.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/service/RoomService.java
>          Map<Integer, Integer> graph = new HashMap<>();
`nit` 스트림을 활용해보면 좋을 것 같습니다.

2022-05-27 16:52 UTC, Hyune-c commented on BE/src/test/java/team21/airbnb/controller/RoomControllerTest.java
> +                .willReturn(new RoomChargeDistributionResponse(MIN_ROOM_CHARGE, MAX_ROOM_CHARGE,
저는 웹 레이어 테스트는 하지 않아요 ㅎㅎ
프론트 개발자나 QA가 잡아주기도 하고, 백엔드 개발자가 집중해야 되는 부분은 도메인 영역이라고 생각하기 때문입니다.

웹 레이어를 테스트하시려면 지금의 방법이 보편적이고, stub을 만드는 방법이 있습니다.
하지만 지금 stub까지 공부하시는건 추천하지 않습니다.

2022-05-28 03:36 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/dto/request/RoomChargeDistributionRequest.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
`nit` 
전 dto는 그냥 `@Data`를 쓰는 편이긴 합니다.

2022-05-28 08:45 UTC, dukcode commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +    @GetMapping("/charge_distribution")
제가 전달을 잘 못한 것 같습니다. 해당 API에 기대하는 것은 `특정 가격 범위에 속하는 숙소의 갯수의 분포`입니다.  

 `숙박업소의 가격은 날짜에 상관없이 고정`되어있고  

예를들어 1박에 `15원하는 숙소 1개`, `16원하는 숙소 1개`, `25원하는 숙소 1개`가 있다면  
`10원대 2개, 20원대 1개`로 표현하는 식입니다 (DISTRIBUTION_UNIT이 10일 때)  

따라서 초기에 API설계에 2가지 방법을 생각했습니다.  

1. 가격을 가공해서 가격대에 해당하는 숙소의 갯수를 제공 (ex. 10원대 2개, 20원대 1개)하고 URL은 `/rooms/charge_distribution`으로 설계  
2. 가격을 가공하지 않고 그대로 제공 (ex. 15원, 16원, 25원)하고 URL은. 
`/rooms/charges`로 설계 (data 가공은 fe에게 맡김). 

위와 같이 2가지 방법에서 Dan은 어떤 방법이 더 낫다고 생각하시나요? 아니면 더 적절한 방법이있을까요?

2022-05-28 08:45 UTC, dukcode commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +            @RequestBody RoomChargeDistributionRequest roomChargeDistributionRequest) {
추후 구현할 `방 검색 api`에서 검색 조건이 많아 (checkout, checkin, maxPrice, minPrice, 인원 수 등) GET Body를 사용하려 했습니다.  

따라서 해당 API에서도 큰 이득은 없지만 `GET메서드에 body를 사용`하는 **일관성**을 유지하려는 의도였습니다.  

하지만 이 일관성을 유지한다는 생각 자체가 저만의 생각인 것 같아 관련 내용을 찾아보는 중입니다..

2022-05-28 08:46 UTC, dukcode commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    public int getDistributedRoomCharge(int distributionUnit) {
예를들어 1박에 `15원하는 숙소 1개`, `16원하는 숙소 1개`, `25원하는 숙소 1개`가 있다면  
`10원대 2개, 20원대 1개`로 표현하는 식입니다 (DISTRIBUTION_UNIT이 10일 때)

2022-05-28 08:51 UTC, dukcode commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +            graph.merge(room.getDistributedRoomCharge(DISTRIBUTION_UNIT), 1, Integer::sum);
사실 숙소의 가격을 분류하는 책임 자체가 도메인에 있는것 같지 않아서 서비스레이어에 둔 것인데, 유틸 클래스를 만드는것이 더 좋은 방법 같아보입니다.

2022-05-28 09:08 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +    @GetMapping("/charge_distribution")
https://hyune.gitbook.io/hyune-wiki/and/codesquad/22reviewer/service-dto

전 팀에도 한 리뷰인데 다들 비슷한 고민을 하고 계시는군요.
굉장히 긴 이야기가 될거 같습니다. 
따로 얘기할게요.

2022-05-28 09:13 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/RoomController.java
> +            @RequestBody RoomChargeDistributionRequest roomChargeDistributionRequest) {
> GET에 payload를 사용하지 않는다.

- 강제되지는 않지만 보편적인 GET API 설계 지식입니다.
- 하지만 예시에서 들었다시피 RFC에서도 SHOULD가 제거되었고, 엘라스틱 서치에서도 혼용하고 있습니다.
- 따라서 저라면 payload를 사용하지 않긴 하지만 스타일의 영역이라고 볼 수도 있을 것 같습니다.

2022-05-28 09:15 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    public int getDistributedRoomCharge(int distributionUnit) {
이 정도면 주석 활용이 필요하다고 생각합니다.

2022-05-29 12:52 UTC, merged