[Team-26][FE][이든-도리] 2주차 01 PR 요청
codesquad-members-2022/airbnb pull request #121
Opened 2022-05-31 06:34 UTC by kimyouknow

안녕하세요 어텀. 도리 이든입니다. 이번 pr도 잘부탁드려요😀

# PR 피드백

### 1. 달력 설계 수정

- 달의 마지막 날짜(28, 29, 30, 31)을 구하는 로직 수정
  - `new Date(2022, 5, 0)`이런식으로 0을 사용하면 전달의 마지막 날짜가 선택됩니다. (2022.04.30)
  - 이전에 `32- new Date(2022, 5, 32)` 방식으로도 동일하게 구현할 수 있지만 가독성이 좋지 않아서 사용하지 않았습니다.
- 월요일 시작 → 일요일 시작
  - `new Date().getDay()` 메서드로 요일을 구하면 `일요일이 0`이어서 편함
- 날짜 데이터 구조 → 객체 데이터 구조로 변경

  - jsx 간소화 (if문 로직은 미리 만들기)
  - 배열 안에 객체 요소로해서 추후에 추가 사항을 대비하기

  ```jsx
  const dates = [
    {
      id: new Date(),
      year: new Date().getFullYear(),
      month: new Date().getMonth() + 1, // getMonth()하면 현재 달 -1 값이 나옴.
      date: new Date().getDate(),
      isActiveMonth: boolean,
    },
    {},
    {},
  ];
  ```

  **렌더링jsx**

  ```jsx
  {
    dates.map((day, index) => (
      <S.DayItem isActiveMonth={isActiveMonth}>{day}</S.DayItem>
    ));
  }
  ```

[캘린더 설계](https://www.notion.so/9dc96fe196cf46a3b3de51854aa9fb78)

### 2. 모달 리팩토링

**이전**

`public/index.html`에서 사용자가 `<div id=”modal></div>`를 만들고, `src/components/WindowModal/Portal/index.tsx`에서 `getElementById(”modal”)`로 접근했어야해서 관심사가 분리된 느낌을 받았습니다.

**이후**

public/index.html에서 div태그를 생성하지 않고 `src/components/WindowModal/Portal/index.tsx`에서 `document.createElement('div')`로 id가 modal인 div 태그를 만들었어서 사용했습니다.

### 3. webpack hot module 대신에 react-refresh 사용한 이유 정리

**liveReload**: 파일 변경이 감지되면 `페이지를 다시 로드하고 새로고침`

**hot module replacement**: 모든 종류의 모듈을 새로고침 할 필요 없이 런타임에 업데이트.

**react-fresh-webpack-plugin**: 바뀐 컴포넌트만 다시 렌더링해주는 역할

⇒ 결론적으로, react-fresh-webpack-plugin과 hmr을 사용하고 있습니다. 자세한 내용은 아래 링크에 정리해두었습니다.

[webpack hmr vs react-refresh-webpack-plugin](https://www.notion.so/webpack-hmr-vs-react-refresh-webpack-plugin-01d4ea34cebb42059bf274d8080077da)

# 진행상황

- [x] canvas 학습
- [x] 이전에 svg로 구현한것을 동일하게 canvas로 구현
- [x] typescript react 컴포넌트 배포 성공 (프로젝트에 적용하진 않았습니다)

# **궁금한 점**

모달을 리팩토링하면서 document.`createElement`를 사용해서 dom에 직접 접근했는데, `응집성`을 위해서 어쩔 수 없는 것인지 react에서 다른 방법이 있는것인지 궁금합니다.

2022-05-31 09:25 UTC, HongJungKim-dev commented
차트 구현은 [도리 로직](https://github.com/kimyouknow/codesquad-airbnb/commit/76611d9940c110c96c320bd54845240613d0077f) 공부하여 구현하였습니다.

2022-05-31 12:47 UTC, hongbiii reviewed
이든, 도리 안녕하세요!
내일은 꿀같은 휴일이네용 🥳

마지막 날짜 구하는 방법에서 0을 활용하니까 훨씬 좋네요!
모달에서 `document.createElement`로 직접 element를 만드는 방식은... 개인적인 생각으로는 별로 안 좋은 것 같아요.
리액트에 JSX 문법이 있기 때문에 필요하다면 부모 컴포넌트를 만드는 게 낫지 않을까 싶습니다.
JSX는 리액트에서 내부적으로 [React.createElement](https://ko.reactjs.org/docs/react-without-jsx.html)를 호출하긴 하는데요, createElement와 jsx를 혼합해서 쓰는 것보다는 jsx로 통일하는 게 좋을 것 같다는 것이 제 생각입니당!

포탈을 사용하지 않고 모달을 구현하는 방법도 있어요.
저도 검색해보다가 발견했는데 [이 블로그](https://nakta.dev/how-to-manage-modals-1)에 정리가 잘 되어 있어서 공유드릴게요!
이 블로그에서는 context를 사용해서 구현했네요. :)

어떤 방법이 정답이다 라고 할 수는 없는 것 같아요. 🧐

이어서 리뷰 남길게요!

2022-05-31 13:39 UTC, hongbiii requested changes

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +function renderCalendar({ activeYear, activeMonth }: CalendarProps): Array<RenderDateProps> {
배열을 리턴하고 있는데 render~~~ 라는 네이밍은 어울리지 않는 것 같아요.
렌더 라고 하면 왠지 DOM 엘리먼트를 리턴할 것 같은 느낌이 들어서요!

타입에 제네릭 써보신 시도도 좋네용
배열 같은 경우는 `RenderDateProps[]` 이렇게 간단하게도 많이 씁니다! :)

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +    id: new Date(year, month, date),
id에 객체가 들어가는 건 조금 어색하게 느껴지네요!..
id에는 number나 string을 사용하는 것을 많이 봐서요,
`${year}-${month}-${date}` (문자열)로 아이디 달아줘도 괜찮을 것 같아요.

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +  );
캘린더를 그려내는 방식이 살짝 이해가 안 가는데 혹시 조금만 설명해주실 수 있을까요?
리턴하는 부분을 보니 전체를 감싸는 div 안에 `WeekContainer`가 2개 있는데 달력에 week가 2개만 있다는 게 좀 이해가 안 돼요 ㅠ.ㅠ

위에 있는 WeekContainer는 아마 요일을 표시하는 (일~토) 부분을 그리신 것 같고
아래에 있는 WeekContainer는 실제 날짜가 그려지는 부분인 것 같은데 이름이 같은 컴포넌트를 사용하고 있어서 헷갈렸던 것 같아요!

2022-05-31 13:39 UTC, deprecated-hongbiii commented on FE/src/components/Calendar/index.tsx
> +  // TODO: //  RenderDateProps[] 배열 타입 지정 고려해보기
`RenderDateProps[]`로 표기하는 게 더 가독성이 좋은 것 같아요!

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +// TODO: 6 (getDay()로 얻은 토요일 값): 매직넘버 수정하기
꼭꼭꼭!

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/CalendarModal/index.tsx
> +        <Calendar activeMonth={activeMonth + 2} activeYear={activeYear} />
많이 중복되네요!
결국에는 상태(데이터)를 사용해서 컴포넌트를 렌더링하니까
캘린더 4개에 넣어줄 데이터들을 상태로 관리해볼 수도 있겠어요~~

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/PriceChart/index.tsx
> +  const maxCount = Math.max(...roomCapacities.map(({ count }) => count));
map에서 그대로 리턴하고 있네요?!
혹시 range만, count만 뽑아서 배열을 만들고 싶었던 거라면 `filter` 메서드가 더 적합할 것 같아요 :)

2022-05-31 13:39 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +  );
dates 배열에는 날짜 하루하루가 객체로 들어있는 것 같은데 어떻게 달력모양으로 렌더링시키신 건지도 궁금합니다!

2022-05-31 13:54 UTC, kimyouknow commented on FE/src/components/Calendar/index.tsx
> +  );
언급해주신 것처럼 위에 있는 WeekContainer는 요일을 표시하는 부분이고, 아래 있는 WeekContainer는 날짜를 렌더링하는 부분이었습니다. 

WeekContainer는 grid를 활용해서 격자무늬로 달력모양으로 렌더링했습니다! 

위, 아래 WeekContainer 모두 grid 스타일이어서 같은 styled-component를 사용했는데, 그 부분이 헷갈리네요,,ㅎㅎ 네이밍을 좀 더 고려해보겠습니다

@HongJungKim-dev

2022-05-31 13:59 UTC, HongJungKim-dev commented on FE/src/components/PriceChart/index.tsx
> +  const maxCount = Math.max(...roomCapacities.map(({ count }) => count));
의미적으로 filter가 더 적절하다는 의미일까요?

@kimyouknow

2022-05-31 14:05 UTC, hongbiii commented on FE/src/components/PriceChart/index.tsx
> +  const maxCount = Math.max(...roomCapacities.map(({ count }) => count));
의미적으로도, 메서드의 의도를 생각해 봤을 때도 filter가 맞는 것 같아요!

2022-05-31 14:08 UTC, hongbiii commented on FE/src/components/Calendar/index.tsx
> +  );
아하아하! 답변 감사합니다! :) 👍

2022-06-01 05:13 UTC, kimyouknow commented
`Changes requested`는 저희가 수정하면 merge 해주신다는 의미일까요? 아니면 다음 pr까지 꼭 반영하라는 의미일까요...?ㅎㅎㅎ

우선은 후자로 생각해서 저희가 merge하고 다음pr까지 리뷰남겨주신부분은 꼭 반영하겠습니다!👍

2022-06-01 05:14 UTC, merged

2022-06-01 05:26 UTC, autumninflab commented
네네! 원래는 수정해서 지금 PR에 커밋 올려달라는 뜻인데 merge하시고 다음 PR에 수정사항 반영해주셔도 괜찮습니다. ㅎㅎ
즐거운 휴일 보내세요! 🏖

2022-06-01 05:28 UTC, hongbiii commented
네네! 원래는 수정해서 지금 PR에 커밋 올려달라는 뜻인데 merge하시고 다음 PR에 수정사항 반영해주셔도 괜찮습니다. ㅎㅎ
즐거운 휴일 보내세요! 🏖