[team-07] sally + zzangmin 2주차 첫번째 PR
codesquad-members-2022/airbnb pull request #142
Opened 2022-05-31 08:05 UTC by leezzangmin

안녕하세요 roach!
리뷰해주셔서 감사합니다!

* 진행상황
예약 기능, 예약 상세보기, 숙소 상세보기 구현

[API 명세](https://documenter.getpostman.com/view/19902575/Uz5AqdNL)

2022-06-01 03:38 UTC, tmdgusya requested changes
API 문서 깔끔하고 좋네요 👍 

몇가지 교체하면 좋은 부분들이 있는거 같아요. 그것만 교체하시고 넘어가시죠~

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/address/Address.java
> +    public static final String ADDRESS_TEXT = "%s %s %s";
public 으로 해둔 이유가 있을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/image/Image.java
>  @EqualsAndHashCode(of = "id")
`id` 로만 지정했을때 imageLink 등이 수정되면 변경감지가 안될 수도 있다는 사실을 알고 계신가요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/image/ImageRepository.java
> +    }
혹시 JPA 의 기본 `Repository` 를 안 사용하시는 이유가 있을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/Period.java
> +	protected boolean isAbove(int range) {
기간을 더 긴가? 를 비교하는 것이면 `isLonger` 로 비교하는게 맞지 않을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/Reservation.java
> +    }
이렇게 Arguments 가 많은 경우에는 Builder 를 사용하시면 좀 더 사용하는 입장에서 좋을꺼에요

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationCalculator.java
> +	private static final BigDecimal taxRate = new BigDecimal("0.1");
이건 확장성에 관한 내용인데 이런 정보는 클래스로 분리해서 주입(Injection) 받는게 낫지 않을까요?
다르게 계산해야 할 경우가 생겼을때 확장하기 힘든 구조로 보여요.

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationDetailResponse.java
> +          return images.stream().map(i -> i.getImageLink())
`::getImageLink` 로 대체 가능한지 확인해보셔도 좋을거 같아요

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRepository.java
> +		@Param("checkInB") LocalDate checkInB, @Param("checkOutB")LocalDate checkOutB);
`@Param` 을 적으신 이유가 있을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRequestDto.java
> +@Data
`@Data` 는 좋긴한데 아래와 같은 문제가 있을 수 있어요

https://www.popit.kr/%EC%8B%A4%EB%AC%B4%EC%97%90%EC%84%9C-lombok-%EC%82%AC%EC%9A%A9%EB%B2%95

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +    }
위에 `@Transactional` 이 붙어 있어서 이 메소드에는 명시적으로 적어주진 않아도 될거 같아요

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +            throw new RuntimeException("cannot make reservation");
이유를 단순히 "cannot make reservation" 으로 적는건 좋지 않은것 같아요.
에러를 찾기 힘들어 보여요.

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +    private void isInvolved(Long roomId, Period period) {
`이미 예약된 방인가?` 로 해석되었는데 맞을까요?
메소드 명을 좀 더 알아보기 쉽게 바꿔도 좋을것 같아요. 예를 들면 isAlreadyReservationRoom 등등

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +        }
이 두개의 메소드에서 예외가 발생했을때 예외 메세지만 보고 어떤 이유인지 아실 수 있을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/room/RoomDetailResponse.java
> +    @JsonProperty("isWished")
써주신 이유가 있을까요?

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/test/java/team07/airbnb/reservation/ReservationRepositoryTest.java
> +@ActiveProfiles("dev")
👍

2022-06-01 03:38 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRoom.java
> +	}
`protected` 인 이유가 궁금한데 혹시 알려주실 수 있을까요?

2022-06-01 07:34 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/image/Image.java
>  @EqualsAndHashCode(of = "id")
관리자 화면은 별도로 작업해서, 
예약도 수정까진 작업하지 않았지만, Reservasion 만 바꾸면 될까요? 
(호옥시... 연관관계 맵핑되는 엔티티간 맞춰줘야 되나 궁금해집니다.)

이 시스템에서는 보통 조회 작없들이 많을거라 생각해서 id 만 하는게 효율적이라고 생각했습니다.

혹시나 해서 궁금한 점은 관리자 시스템을 개발한다면,..
@EqualsAndHashCode 등 엔티티 설정 부분들을 동일하게 맞춰 줘야 하나요?

2022-06-01 07:36 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/reservation/Period.java
> +	protected boolean isAbove(int range) {
네, 감사합니다.

2022-06-01 14:57 UTC, leezzangmin commented on BE/airbnb/src/main/java/team07/airbnb/address/Address.java
> +    public static final String ADDRESS_TEXT = "%s %s %s";
작업하며 실수한 것 같습니다. ㅜㅜ private으로 변경하겠습니다!

2022-06-01 15:04 UTC, leezzangmin commented on BE/airbnb/src/main/java/team07/airbnb/image/ImageRepository.java
> +    }
아 영한님 강의를 보면서 작성하다가 EntityManager로 DB CRUD를 하시길래 이게 당연한 건줄 알았습니다.
이후에 작업한 코드들은 CrudRepository나 JpaRepostory를 구현해서 사용하는데, 이 코드도 수정하도록 하겠습니다!

2022-06-01 15:08 UTC, leezzangmin commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationCalculator.java
> +	private static final BigDecimal taxRate = new BigDecimal("0.1");
Bean을 만들어서 생성자로 주입받거나
따로 주입받는 코드를 작성해서 사용하는 것이 좋다는 말씀이시죠?
처음에는 유틸 클래스로 분리하는 것을 생각했는데, 좋은 코드를 고민해보고 적용해보겠습니다!

2022-06-01 15:14 UTC, leezzangmin commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRepository.java
> +		@Param("checkInB") LocalDate checkInB, @Param("checkOutB")LocalDate checkOutB);
명시적으로 Parameter를 넣어준다는 의미가 강해지는 것 같아서 개인적으로 코드 읽기가 편한 느낌이 들어서 생략하지 않는 편입니다.
현업에서는 주로 생략하는 것을 선호하시겠..지요...?

2022-06-01 15:19 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +    private void isInvolved(Long roomId, Period period) {
넵, 알겠습니다 ^^

2022-06-01 15:21 UTC, leezzangmin commented on BE/airbnb/src/main/java/team07/airbnb/room/RoomDetailResponse.java
> +    @JsonProperty("isWished")
isWished가 json형식으로 리턴되었을 때 
"wished" 라는 이름으로만 나가는 현상이 생겨서 명시하게 되었습니다.
제이슨맵퍼 버전 문제라고 하는데, 혹시 해결방법이 더 있을까요?

https://multifrontgarden.tistory.com/269

2022-06-01 15:25 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRoom.java
> +	}
패키지 내에서만 사용돼서 접근제어자를 썼는데, default 랑 헷갈린 것 같습니다. ㅎㅎ

2022-06-01 15:55 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +            throw new RuntimeException("cannot make reservation");
클라이언트로 전달할 메시지로만 생각했습니다.
추후에 예외처리 추가해서 관련된 필드, 요청 등 응답으로 보낼 생각으로,
좀 더 생각지 못했던 것 같습니다.

BE에서 에러원인을 찾기 위한 에러 메시지는... 
ExceptionHandler에서 에러 발생된 곳을 로그로 남기도록 하면 될까요?
아니면, 언급 해주신 대로 에러 이유를 메시지로 적는 게.... 맞을까요?

2022-06-01 15:57 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +        }
모를 것 같습니다.  ㅎㅎ 
이유를 알 수 있도록 고민해보고, 수정하도록 하겠습니다.

2022-06-02 01:59 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/image/Image.java
>  @EqualsAndHashCode(of = "id")
@sally-ksh 
아 요건 제가 값객체와 헷갈렸네요 id 로 만 해줘도 dirtychecking 이 잘될거에요

2022-06-02 02:01 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationCalculator.java
> +	private static final BigDecimal taxRate = new BigDecimal("0.1");
네네~! 따로 Class 로 분리해서 주입받는 방식으로 적는게 좋은거 같아요

2022-06-02 02:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationRepository.java
> +		@Param("checkInB") LocalDate checkInB, @Param("checkOutB")LocalDate checkOutB);
아하 보통 생략하는데 뭐 이건 두분이서 맞춰주기만 하면 상관없는 문제에요~
단순 컨벤션 문제라

2022-06-02 02:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/reservation/ReservationService.java
> +            throw new RuntimeException("cannot make reservation");
에러 이유를 적어주세요. 에러 메세지만 보고도 어떻게 에러가 발생했는지 정확히 판단되도록요

2022-06-02 02:03 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/room/RoomDetailResponse.java
> +    @JsonProperty("isWished")
아하 그것때문이였군요. 그러면 그냥 둬도 될것 같아요

2022-06-02 04:23 UTC, tmdgusya commented
일단 다음 미션 하시게 머지해드릴께요~

2022-06-02 04:23 UTC, merged