[BE] Team-14 2주 1차 PR 요청
codesquad-members-2022/airbnb pull request #152
Opened 2022-05-31 08:19 UTC by naneun

충돌 해결 중입니다.

2022-06-01 13:45 UTC, wheejuni requested changes
수고 많으셨습니다. 💯 
전반적으로 괜찮은데요, 몇가지 의견 드립니다.

2022-06-01 13:45 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
> +    }
이제는 `@AllArgsConstructor` 사용하셔도 됩니다 ㅎㅎ

2022-06-01 13:45 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/dummy/DummyDataService.java
> +        JsonNode row = localdata_031101.get("row");
`ObjectMapper` 로 `List<T>` 를 받아서 하나씩 순회하면 되는 것 아니었을까요?
어떤 고민 끝에 이렇게 구현하셨는지 궁금합니다~

2022-06-01 13:45 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/room/domain/ReviewRepository.java
> +    @Query("select new com.team14.cherrybnb.room.dto.ReviewSummary(count(r.id), avg(r.starRating)) from Review r where r.room = :roomId")
엔티티 그대로 가져온 후 DTO로 가공하는 형태였으면 합니다.

2022-06-01 13:45 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/room/domain/RoomRepository.java
> +            "join fetch r.address " +
엔티티 클래스에서 애노테이션을 이용해서 더 좋게 풀 수 있는 방법은 없을까요?

2022-06-02 02:37 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
> +    }
네 적극적으로 사용하겠습니다!~ 🙆‍♂️🙆‍♂️

2022-06-02 03:02 UTC, CMSSKKK commented on backend/src/main/java/com/team14/cherrybnb/dummy/DummyDataService.java
> +        JsonNode row = localdata_031101.get("row");
dummyData를 넣는 api를 현재 api를 사용할지, csv파일로 넣을 지 아직 정확하게 정하지 않았습니다. 

임시로 데이터를 넣어보기 위해서 하드코딩으로 구현했습니다. 현재 로직을 삭제하거나 말씀해주신것처럼 리팩토링해보겠습니다.

2022-06-02 03:04 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/room/domain/RoomRepository.java
> +            "join fetch r.address " +
@EntityGraph 를 말씀하시는 거라면 한 번 사용해보도록 하겠습니다! 🙆‍♂️🙆‍♂️

2022-06-02 03:07 UTC, CMSSKKK commented on backend/src/main/java/com/team14/cherrybnb/room/domain/ReviewRepository.java
> +    @Query("select new com.team14.cherrybnb.room.dto.ReviewSummary(count(r.id), avg(r.starRating)) from Review r where r.room = :roomId")
엔티티 그대로 받아오는 것을 권장하시는 이유가 궁금합니다! 

표현계층과의 결합도 문제일까요??

2022-06-02 05:11 UTC, merged