[Team-05][BE] 비씨 & 노리  airbnb 프로젝트 1주차 첫 번째 PR
codesquad-members-2022/airbnb pull request #17
Opened 2022-05-25 07:59 UTC by nohriter

안녕하세요 5조 비씨 노리 입니다 😄

설계를 고민하는 과정에서 시간이 많이 소요되어 진행을 못했습니다.

앞으로 3주 동안 열심히 진행해 보겠습니다. 잘 부탁 드립니다. 🙇

## 📝  진행 상황
- [요구사항 분석](https://docs.google.com/spreadsheets/d/1DIlvem5j0Jp4o77ZXtCk0_1GCblrjjO6aN78SERpIw/edit#gid=1585970172)
- [그라운드 룰 작성](https://github.com/honeySleepr/airbnb_team-05/wiki)
- 연관관계 매핑 고민 중

## ✨ 질문사항
- 프로젝트 시작 후 설계가 어려운 것 같습니다. 이번에 저희는 ERD를 그리지 않고 대략적인 기능 파악 후 api를 먼저 구현하고 있는데 기획서를 보고 데이터를 정리한 다음 ERD를 먼저 그리는게 좋은지,  단은 어떤 방식으로 진행하시는지 궁금합니다.

2022-05-25 09:38 UTC, Hyune-c reviewed
수고하셨습니다.
jpa 에 관련된 테스트를 많이 해보시면 좋을 것 같고, idea 관련은 gitignore 하실 수 있으실 것 같아요.

---


> 프로젝트 시작 후 설계가 어려운 것 같습니다. 이번에 저희는 ERD를 그리지 않고 대략적인 기능 파악 후 api를 먼저 구현하고 있는데 기획서를 보고 데이터를 정리한 다음 ERD를 먼저 그리는게 좋은지, 단은 어떤 방식으로 진행하시는지 궁금합니다.

- ERD를 먼저 그리는 방법은 전통적인 방법으로 백엔드 개발자에게 익숙한 방법입니다.
하지만 소위 말하는 DB 중심 설계가 될 수 있습니다.
- 반면 API를 먼저 설계하는 경우는 추상체를 먼저 만들기에 로직을 추상화할 수 있지만
이후 도메인과 entity를 매핑해야되는 수고가 들어갑니다.

둘 다 좋은 방법입니다. 하지만 실무에서 해본 경험을 생각해보면 API를 먼저 설계했던 것 같습니다.

- 보통 기획의 니즈를 충족하는 API를 먼저 만들었습니다.
- 레거시는 이미 구현된 거대한 테이블이 있고 변경이 힘들기에 매핑 작업을 위해 native query를 사용하기도 했습니다.

2022-05-25 09:38 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/Bnb.java
> +	@Id @GeneratedValue
@GeneratedValue의 strategy를 명시하는 것과 하지 않는 것에는 무슨 차이가 있을까요?

2022-05-25 09:38 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/wishlist/WishController.java
> +    }
`nit` 
lombok을 활용할 수 있을 것 같아요.

2022-05-25 09:38 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/wishlist/WishService.java
> +    //todo 미완성 진행중
👍

2022-05-25 12:07 UTC, Hyune-c requested changes
수정 부탁드립니다.

2022-05-26 02:01 UTC, nohriter commented on Backend/src/main/java/project/airbnb/bnb/Bnb.java
> +	@Id @GeneratedValue
`@GeneratedValue`의 `strategy`를 명시하지 않았을 경우 `@GenerationType.strategy`의 기본값인 AUTO 전략으로 선택됩니다. AUTO 전략의 경우 선택한 데이터베이스 방언에 따라 IDENTITY, SEQUENCE, TABLE 전략 중 하나를 자동으로 선택하며, AUTO 전략의 장점으로는 데이터베이스를 변경해도 코드를 수정할 필요가 없다는 장점이 있습니다. 데이터베이스 변경이 없다면 명시적으로 전략을 표기 하는것이 좋을까요 ?

2022-05-26 02:01 UTC, nohriter commented on Backend/src/main/java/project/airbnb/wishlist/WishController.java
> +    }
넵 사용하도록 하겠습니다 😁

2022-05-26 02:09 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/Bnb.java
> +	@Id @GeneratedValue
https://hyune.gitbook.io/hyune-wiki/and/codesquad/22reviewer/airbnb
- JPA entity의 식별자 기본 생성 전략에 대한 리뷰

배경 지식은 공부가 되신 것 같습니다.
`데이터베이스 방언에 따라 IDENTITY, SEQUENCE, TABLE 전략 중 하나를 자동으로 선택하며` 누가 선택하는지에 대해 좀 더 생각해보신 후 링크를 봐주세요.

2022-05-26 02:27 UTC, Hyune-c approved these changes
수고하셨습니다.

2022-05-26 02:33 UTC, merged

2022-05-26 04:48 UTC, honeySleepr commented on Backend/src/main/java/project/airbnb/bnb/Bnb.java
> +	@Id @GeneratedValue
오오 MySQL default가 Table 전략으로 바뀌었군요..! Identity로 설정해주도록 하겠습니다
정보 감사합니다!