[Team-08][BE][후&아더] - 로컬DB 환경구성, 엔티티 작성 및 연관관계 매핑, 숙박 요금 계산 API 구현
codesquad-members-2022/airbnb pull request #177
Opened 2022-06-02 01:49 UTC by ak2j38

안녕하세요 시그리드 👋
`hoo` 와 `Ader`입니다!
이번주도 잘 부탁드립니다! 
- - -

## 기능 구현 목록
- [x] 로컬 DB 환경 구성
  - [x] 도커를 이용한 Mysql
- [x] 엔티티 클래스 작성
- [x] 엔티티간 연관관계 매핑   
- [x] 비즈니스 요구사항 분석, 필요한 정책들과 정책별 요금 산정 방법 정하기
- [x] 정해진 요금정책 내용을 구현체로 구현하기
- [x] RoomRepository 구현 - `findById`
- [x] ReservationService - 요금 계산 서비스 구현
- [x] 테스트코드 작성
- [x] ReservationController - 찐서비스로 갈아끼우기
- - -

## 요금정책 기준
<img width="486" alt="스크린샷 2022-06-02 오전 10 47 21" src="https://user-images.githubusercontent.com/29879110/171529755-0b431f98-390c-4b58-a6e2-8cb4544e852e.png">
- - -

## 고민 사항은 코멘트에 추가했습니다!

2022-06-02 01:58 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
> +    List<ChargePolicyType> findActiveChargePolicyTypeById(Long id);
쿼리를 작성하면서 궁금한 점이 생겼습니다. 아래 2가지 방법 중 어떤 방법이 더 효율적이면서 JPA의 취지에 맞는지 궁금합니다.

1) `@Query`를 직접 쿼리문으로 필터링
2)  `find()`로 전부 결과를 가져와서 자바코드에서 필터링

2022-06-02 02:04 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +    }
테스트 코드를 위해 더미데이터를 생성하던 중 `Room`과 `RoomChargePolicy`간의 순환참조가 발생해서 `setter` 메소드를 추가했습니다. 

혹시 `setter`를 사용하지 않는 아주 우아한 방법이 있을까요?

2022-06-02 02:16 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
> +    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.getInstance(), AccommodationTaxChargePolicy.displayName());
각 요금정책의 구현체들은 싱글톤으로 구현했습니다.(스프링 관리 X) 

2번 째 인자인 각 요금정책의 구현체의 인스턴스를 넣어주는 부분을 스프링이 관리해주는 싱글톤 방식으로 사용하고 싶었는데 `.getBean()`을 사용하는 것이 좋아보이지 않아 셀프로 싱글톤을 구현했습니다. 

Q) 셀프로 싱글톤을 구현해서 적용해도 괜찮을까요?

2022-06-02 02:19 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
> +    private final ReservationService reservationService;
실제 `ReservationService` 개발이 끝나면 `MockReservationService`는 프로젝트에서 삭제할 예정입니다.

2022-06-03 06:43 UTC, sigridjineth commented
명일 새벽까지 리뷰가 진행될 예정입니다 :)

2022-06-03 06:46 UTC, who-hoo commented
> 명일 새벽까지 리뷰가 진행될 예정입니다 :) 다소 늦어진 점 양해 부탁드립니다. (__)

녜헹~~~~~~~

2022-06-03 14:41 UTC, sigridjineth requested changes
구현하신 사항이 많네요. 같이 이야기해보면 좋을 것 같은 지점이 많아서, 이번 리뷰에는 Request changes 드렸습니다.
확인해주시고 답변 부탁드릴게요.

2022-06-03 14:41 UTC, realsigridjin commented on BE/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
Gradle에서 `compileOnly` 와 `runtimeOnly` 의 차이점이 무엇일까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/ChargePolicy.java
> +    @Column(name = "name")
DB 칼럼에 저장되는 필드명을 상이하게 가져가신 이유가 있으실까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/MemberType.java
> +    GUEST("게스트"), HOST("호스트");
enum 타입의 도입 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private int headcount;
이전에도 이야기 했지마는.. 저는 Entity의 필드값은 웬만하면 Wrapper Type으로 가져가는 것이 좋다고 생각하는 입장입니다. [링크](https://stackoverflow.com/questions/2331630/entity-members-should-they-be-primitive-data-types-or-java-data-types)

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    @OneToMany(mappedBy = "room", cascade = CascadeType.REMOVE, orphanRemoval = true)
JPA를 공부하다보면.. 연관관계 매핑이나 영속성의 전이나 이런 개념들이 정신나가게 어렵죠?
`CascadeType.REMOVE`와 `orphanRemoval = true` 는 어떤 차이일까요? 어떤 상황에서 사용에 주의해야 할까요?
스스로 테스트를 해보시면서 학습해보시고, 본인만의 언어로 알게 된 사항을 한판 정리 부탁해요.

키워드: 부모 엔티티와 자식 엔티티의 관계

[학습할 만한 링크](https://www.objectdb.com/java/jpa/persistence/delete#Orphan_Removal_)

[학습할 만한 링크 2](https://stackoverflow.com/questions/18813341/what-is-the-difference-between-cascadetype-remove-and-orphanremoval-in-jpa)

[학습 테스트 어떻게 하는가](https://github.com/da-nyee/jpa-learning-test)

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    @OneToMany(mappedBy = "room", cascade = CascadeType.REMOVE, orphanRemoval = true)
CascadeType 에도 어떤 것들이 있는지 살펴보시면 좋을 것 같습니다. 타입 중에 `PERSIST` 는 함부로 쓰면 안된다고들 하는데요, 왜 그럴까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@ExtendWith(MockitoExtension.class)
MockitoExtension과 SpringExtension은 서로 어떤 차이가 있을까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +    @InjectMocks
InjectMock과 Mock, 그리고 Spy의 차이는 무엇일까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +    @DisplayName("존재하는 roomId에 해당하는 숙소의 1박당 요금, 총 요금, 상세 요금 항목들을 계산하여 리턴한다.")
상세한 설명이 좋습니다 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +    void calculateTotalChargeOfSuccessTest() {
한글로 작성해주셔도 됩니다. 독자 대상이 한국어 사용자일 것이므로, 지금은 영어 대신 한국어를 사용합시다.
```suggestion
    void roomId에_해당하는_요금을_계산가능하다() {
```

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +        assertThat(roomChargeResponse.getChargePerDay()).isEqualTo(expected.getChargePerDay());
`assertAll` 에 대해 학습해보고, 이를 활용하여 테스트 확언문을 감싸봅시다.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +        assertThatThrownBy(() -> reservationService.calculateTotalChargeOf(roomId, requestParam))
해당 테스트 코드에서 `assertThatThrownBy`의 사용이 훌륭합니다 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/resources/application.yml
> +    password: 1234
개발용 yml을 만들어서 production과 분리해보세요.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomDetailResponse.java
> +    private ImagesResponse imagesResponse;
Dto로의 변환 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
> +    List<ChargePolicyType> findActiveChargePolicyTypeById(Long id);
결국 선택의 영역이겠죠. 쿼리문으로 필터링해서 가져오면, 자바 클래스 단에서 처리하는 퍼포먼스보다 쿼리문을 최적화했을 때 얻을 수 있는 성능적 이점이 있겠죠. 그런데 자바 클래스 단에서 필터링하면 조금 더 객체지향적으로 접근할 수 있겠죠. 현재 구현 단계에 따라 엔지니어가 판단해야 할 선택의 영역이라고 생각합니다.

조금 더 쿼리가 복잡해지면 여유가 있다는 가정 하에 QueryDSL 도입을 검토해보세요. 쿼리 복잡도를 감소시키는 점과 함께 Entity 필드 값이 변경되었을 때 수동으로 체크하지 않아도 된다는 장점이 있습니다.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
> +	public static RoomChargeResponse of(int chargePerDay, int totalCharge, ChargesResponse chargesResponse) {
`of`의 사용이 좋아보입니다 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
> +@Primary
`@Qualifier` 와 `@Primary` 는 서로 어떻게 다를까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice
`RestControllerAdvice`의 사용 짱짱맨 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/exception/ErrorResponse.java
> +    private String errorMessage;
분리 좋네요 👍

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/resources/sql/schema.sql
> +        REFERENCES room (id) ON DELETE RESTRICT ON UPDATE RESTRICT;
`ON DELETE` 와 `ON UPDATE` 의 사용이 좋은데요. `RESTRICT` 가 기본값임에도 불구하고 명시해주셔서 가독성이 높아졌습니다.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/resources/sql/schema.sql
> +    `rate`       DECIMAL(3, 2) NOT NULL COMMENT '별점',
`UNSIGNED` 속성 을 넣어주셔도 좋을 것 같네요. 별점에는 마이너스 값이 없으니까요.

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/resources/sql/schema.sql
> +CREATE UNIQUE INDEX UQ_charge_policy_1
unique index와 primary key의 차이가 있다면 무엇일까요?

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/resources/sql/schema.sql
> +    `type`              VARCHAR(5)  NOT NULL COMMENT '회원타입(G: 일반, H: 호스트)',
`nit`
MySQL에서 꼭 `enum` 타입이 모든 상황에서 나쁜 것이 아닙니다. unpopular opinion을 소개해 드립니다. [링크](https://saveriomiroddi.github.io/Impact-of-ENUM-data-type-on-MySQL-data-storage/)

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/resources/application.yml
> +    org.hibernate.SQL: debug
만약 logger를 사용하게 된다면, TRACE 옵션도 켜주시기를 추천드리겠습니다. [링크](https://kwonnam.pe.kr/wiki/java/hibernate/log)
`log4j.logger.org.hibernate.type=TRACE`

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
👍 👍 👍

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
>              new MemberResponse(1L, "ahoo", "https://avatars.githubusercontent.com/u/68011320?v=4"),
`@Profile` 을 사용해서, 테스트를 위한 프로파일인 경우에만 빈이 등록되도록 수정해보시길 바랍니다.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private int headcount;
RoomImage 정도의 객체면 굳이 PK가 부여될 필요가 없으므로 `@ElementCollection` 을 도입하는 것도 괜찮다고 생각합니다. 단, 이런 경우에는 RoomImage가 VO여야 하겠죠. Entity가 아니라...

```java
@Embeddable
public class Image {
```

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
사실 `@Transactional` 클래스 레벨에 명시하는 것은 비추합니다. 메소드 레벨에 선언해주세요.
https://stackoverflow.com/questions/27647608/spring-transactional-on-class-vs-on-method?lq=1

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
> +    private static final WeeklyDiscountChargePolicy instance = new WeeklyDiscountChargePolicy();
더 좋은 변수명을 고민해주세요.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
> +    public RoomChargeResponse calculateTotalChargeOf(Long roomId, RoomChargeRequest roomChargeRequest) {
하나의 함수가 너무 많은 일을 하고 있습니다. 테스트 코드를 작성하시고, 이를 바탕으로 리팩토링을 진행해주세요.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
> +        int totalCharge = charges.getCharges().values().stream()
직접 데이터를 꺼내서 작업하는 것이 아니라, `charges`가 직접 값을 더하는 행위를 수행해서 객체가 직접 결과값을 반환하도록 구현해주세요.

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/test/java/com/ahoo/airbnb/data/TestData.java
> +    static {
`CommandLineRunner` 이용해서 초기 데이터를 로드하는 방법에 대해 고민해보세요.

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private Room room;
일대다 양방향의 경우, 두 엔티티 모두 다 같은 키를 관리하므로 문제가 발생할 수 있기 때문에 반대편인 다대일 쪽은 `insertable`, `updatable` 설정으로 읽기만 가능하도록 구현하면 어떨까요?

[참고할 만한 링크](https://stackoverflow.com/questions/3805584/please-explain-about-insertable-false-and-updatable-false-in-reference-to-the-jp)

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    private List<RoomChargePolicy> roomChargePolicies = new ArrayList<>();
혹시 `@JoinTable` 전략에 대해 아시나요? 모르신다면 공부해보시고 적용 여부를 검토해보세요.

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomImage.java
> +    private Room room;
여기도 마찬가지입니다. 꼭 `RoomImage` 쪽에서 Room을 참조해야 하나요? 구현 상 양방향 참조가 필요한 지 검토해주세요.

2022-06-03 14:41 UTC, realsigridjin commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +    private Room room;
꼭 `RoomChargePolicy` 쪽에서 Room을 참조해야 하나요? 구현 상 양방향 참조가 필요한 지 검토해주세요.
그리고 Entity가 아니라 VO로 선언해야 하지 않을까요? `RoomChargePolicy`는 엔티티 취급을 할 정도로 중요한 객체가 아니라고 생각합니다.

2022-06-03 14:41 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +        this.room.getRoomChargePolicies().add(this);
어딘가 어색해보이지 않나요? `RoomChargePolicy`는 하나의 정책에 불과한데, 정책에다가 `Room`을 설정한다. 어딘가 주객전도 되었다는 느낌을 받았습니다. 이게 최선인지 한 번만 더 고민해주시고 이야기를 나눠보도록 하죠!

2022-06-03 14:42 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
> +    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.getInstance(), AccommodationTaxChargePolicy.displayName());
스프링이 관리해주는 싱글톤 방식을 굳이 사용하지 않으시는 이유가 있나요? 저는 크게 문제가 없지 않을까 하는 의견입니다.

2022-06-04 06:32 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
> +    List<ChargePolicyType> findActiveChargePolicyTypeById(Long id);
> 현재 구현 단계에 따라 엔지니어가 판단해야 할 선택의 영역이라고 생각합니다.

저의 의견은 현재 구현 단계에서는 데이터가 많지 않으므로 자바 클래스 단에서 처리하는 것이 더 좋을 것 같아요! @ak2j38의 의견은~?

2022-06-04 06:36 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
> +    List<ChargePolicyType> findActiveChargePolicyTypeById(Long id);
> 저의 의견은 현재 구현 단계에서는 데이터가 많지 않으므로 자바 클래스 단에서 처리하는 것이 더 좋을 것 같아요! @ak2j38의 의견은~?

저의 의견도 현재는 자바 소스에서 필터링 해보는 연습을 진행하면 좋을 것 같아요! 🥕

2022-06-04 06:59 UTC, who-hoo commented on BE/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
`compileOnly`와 `runtimeOnly`의 차이점
  - `compileOnly`는 `compileClassPath`에만 추가 -> 컴파일시에만 필요하고 런타임에는 사용하지 않는 의존성들을 추가
  - `runtimeOnly`는 `runtimeClassPath`에만 추가 -> 컴파일 타임에는 필요없는데 런타임에서는 의존하는 것들을 추가
  - (ClassPath : 클래스나 jar 파일이 존재하는 위치)
  - 이렇게 분리해주면, 빌드 결과물의 사이즈가 줄어들고 불필요한 순간에 컴파일을 다시 하지 않아도 되는 장점이 있습니다

[참고자료 - Gradle - The Java Library Plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)

---

늘 아무생각 없이 복붙으로 의존성 추가 했었는데, 학습할 거리 알려주셔서 감사합니다~ 👍

2022-06-04 06:59 UTC, ak2j38 commented on BE/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
추가로 다른 의존성 옵션들에 대해서 학습해보았습니다!

`Implementation`은  의존 라이브러리를 수정할 때 현재 모듈까지만 재빌드되어 현재 모듈을 의존하고 있는 다른 모듈들은 수정된 의존 라이브러리를 사용할 수 없습니다.

`api`는 의존 라이브러리를 수정할 때 현재 모듈을 의존하고 있는 다른 모듈들도 재빌드되어 수정된 의존라이브러리를 사용할 수 있게 됩니다.

`annotationProcessor`는 annotataion processor를 명시하는 옵션으로 `lombok`을 설정하는데 필요합니다.

`testImplementation`은 프로젝트의 테스트 소스를 컴파일하고 실행하는데 필요한 종속성입니다.

2022-06-04 07:03 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/ChargePolicy.java
> +    @Column(name = "name")
처음에는 요금정책들을 `ENUM`으로 관리할 생각을 하지 못한채 DB 테이블을 먼저 설계해서 DB컬럼명과 필드명이 달라졌습니다 😂
또한 DB에서는 요금 정책의 이름이라는 개념으로 컬럼이 정해져 `name`이라는 네이밍이 어색하지 않게 느껴졌습니다.....

2022-06-04 07:23 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private int headcount;
> 이전에도 이야기 했지마는.. 저는 Entity의 필드값은 웬만하면 Wrapper Type으로 가져가는 것이 좋다고 생각하는 입장입니다.

현재 DB에 `NotNull` 속성들이 있어 의도한 대로 값이 들어올 것이라고 판단했는데 시그리드 의견은 `headcount` 필드에 0이 아닌 `null`로 들어와 `NPE`를 처리하는 로직을 넣는 것이 더 좋다는 의견이실까요??

> RoomImage 정도의 객체면 굳이 PK가 부여될 필요가 없으므로 @ElementCollection 을 도입하는 것도 괜찮다고 생각합니다. 단, 이런 경우에는 RoomImage가 VO여야 하겠죠. Entity가 아니라...

`@ElementCollection`에 대해서 학습을 해보았고 현재 저희 프로젝트 상황에 도입을 고려해보기로 했습니다!

2022-06-04 07:29 UTC, who-hoo commented on BE/src/main/resources/application.yml
> +    password: 1234
프리티어 한도때문에 6월에 새로 운영 DB 환경을 구성하였습니다. 현재 개발, 운영 환경 설정을 분리하여 구현([해당 피처 개발 브랜치](https://github.com/ak2j38/airbnb/tree/feature/db-configProd-%2373))해두었고 다음 PR에 포함시키도록 하겠습니다!

2022-06-04 07:32 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice
@ak2j38 쌍따봉 dㅎ_ㅎb

2022-06-04 07:54 UTC, ak2j38 commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +    @InjectMocks
`@Mock`은 필요한 클래스에 대한 모의 객체를 만들어줍니다.
`@InjectMocks`은 클래스의 인스턴스를 생성하고 `@Mock`, `@Spy`로 생성된 모의객체를 해당 인스턴스에 주입합니다. 

`@Spy`은 `@Mock`과 같이 필요한 클래스에 대해 모의 객체를 만들지만 stub한 메소드를 제외하면 나머지는 해당 클래스의 실제기능을 그대로 사용합니다.

2022-06-04 07:55 UTC, who-hoo commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@ExtendWith(MockitoExtension.class)
- `SpringExtension`: 스프링 테스트 프레임워크가 필요할 경우 사용 
- `MockitoExtension`: 스프링 테스트 프레임워크가 필요하지 않고, Mockito만을 사용할 때 사용

ex) 스프링 테스트 프레임워크가 제공하는 `@MockMvc`와 같은 기능을 사용할 때는 `SpringExtension`을, 스프링 테스트 프레임워크에 대한 의존성 없이 Mockito만을 사용할 때는 `MockitoExtension`을 사용합니다!

---
[참고자료 spring-test](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#testing-introduction)

2022-06-04 08:00 UTC, sigridjineth commented on BE/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
현업에서는 컴파일되는 최종 빌드 파일의 크기를 줄어야 하는 경우가 있습니다. 따라서 컴파일 타임과 런타임을 고민해야 하는 지점이 분명 생기게 될 것입니다.

2022-06-04 08:05 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/entity/ChargePolicy.java
> +    @Column(name = "name")
변수명이 다르면 혼란을 유발할 수 있습니다. 그리고 이전에 작업한 변수명을 쉽게 바꿀 수가 없다는 것이 바로 기술부채가 된다는 뜻이겠쥬.

2022-06-04 08:09 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private int headcount;
네, 저는 코드 레벨 단에서도 명시적으로 표현해야 한다고 생각합니다. 왜냐하면 DB 스키마는 바뀔 수 있고 코드 레벨과는 또 다른 환경이기 때문에 서로 독립적으로 관리되어야 한다고 생각해요. 만약에 이 클래스가 MySQL이 아니고 전혀 다른 DB 구현체에 붙을 수도 있으니까요. NPE를 명시적으로 처리하는 것이 예측 가능한 설계라고 저는 생각합니다.

2022-06-04 08:16 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +        this.room.getRoomChargePolicies().add(this);
말씀하신 하나의 정책은 `ChargePolicy`입니다. 
`RoomChargePolicy`는 해당 `Room`에 적용되어 있는 `ChargePolicy`로서 다대다 관계를 일대다 다대일 관계로 풀어내는 과정에서 만들어진 객체입니다.

2022-06-04 08:26 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +    private Room room;
`RoomChargePolicy`는 Room(숙소)와 ChargePolicy(요금 정책) 간의 다대다 관계를 일대다, 다대일 관계로 풀어주기 위해 두었습니다. 

Room-RoomImage, Room-RoomChargePolicy와 같은 일대다관계에 있어서 꼭 RoomImage나 RoomChargePolicy에서 Room을 참조해야할까와 같은 고민을 이미 했었는데요,, 
실제로 [일대다 단방향으로 수정](https://github.com/codesquad-members-2022/airbnb/pull/177/commits/e0aaa2058b38972eaf59719bd232c44fdc814624)하고 나니, 일대다 단방향 관계의 단점들을 뒤늦게 알게 되어서 다시 양방향 관계로 바꾸어 주었습니다.

다시 양방향 관계로 바꾼 이유는 다음과 같습니다.
1. 엔티티 그래프 탐색을 하려면 엔티티가 끊어지면 안되서
2. 본인 테이블에 외래키가 있으면 엔티티의 저장과 연관 관계 처리를 insert sql 한번으로 끝낼 수 있지만, 다른 테이블에 외래키가 있으면 연관관계 처리를 위한 update sql을 추가로 실행해야하기 때문에

이런 문제들을 앞서 알려주신 `@ElementCollection`을 사용하면 해결이 가능할지 조금 더 학습해보도록하겠습니다ㅎㅎ!

2022-06-04 08:41 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    private List<RoomChargePolicy> roomChargePolicies = new ArrayList<>();
`@JoinTable` 전략에는 4가지가 존재합니다.
1. `일대일 조인테이블`
2. `일대다 조인테이블`
3. `다대일 조인테이블`
4. `다대다 조인테이블`


현재 저희 프로젝트에서는 `Room`과 `ChargePolicy`간의 다대다 관계가 존재하므로 4번의 경우를 적용할 수 있는지 공부해보겠습니다!

2022-06-04 08:47 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private Room room;
너무 좋아요! 👍 ❤️

2022-06-04 08:53 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomImage.java
> +    private Room room;
ditto; 아래 코멘트와 동일한 내용입니다!

2022-06-04 08:55 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
> +        int totalCharge = charges.getCharges().values().stream()
`ChargeResponse`클래스는 `DTO`인데 내부의 로직이 있어도 될까요??

2022-06-04 09:03 UTC, ak2j38 commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
조회 로직에서는 `@Transactional`이 필요없고 수정, 삭제 등에서만 필요해서 메소드 레벨에 선언하는 것을 추천하시는 걸까요?

또한 저희의 뇌피셜인데 `@Transactional`을 클래스 레벨에 선언하면 `SELECT` 수행 중 락이 걸려 수정, 삭제의 처리가 늦어질 가능성이 있는건가요?

2022-06-04 09:05 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
>              new MemberResponse(1L, "ahoo", "https://avatars.githubusercontent.com/u/68011320?v=4"),
`@Profile` 어노테이션을 적용해 테스트때만 적용되도록 수정하겠습니다!

2022-06-04 09:34 UTC, ak2j38 commented on BE/src/main/resources/sql/schema.sql
> +CREATE UNIQUE INDEX UQ_charge_policy_1
`unique key`는 null 값을 허용합니다.
반면에 `primary key`는 null 값이 **절대로** 허용되지 않습니다!

2022-06-04 09:39 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private int headcount;
래퍼 타입으로 일괄 변경하였습니다 감사합니다 😆

2022-06-04 09:43 UTC, who-hoo commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +    void calculateTotalChargeOfSuccessTest() {
읽기에도 좋고, 못하는 영작 때문에 고민도 안해도 되고 너무 좋네요ㅎㅎ 한글메서드명으로 변경하였습니다 감사합니다 😆

2022-06-04 09:52 UTC, who-hoo commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +        assertThat(roomChargeResponse.getChargePerDay()).isEqualTo(expected.getChargePerDay());
- `assertAll`을 사용하면 `assert`문 수행 중 실패하는 케이스가 있어도 중간에 테스트를 멈추지 않고 `assertAll`로 감싸진 `assert`문을 전부 실행합니다!

중간에 실패하는 케이스가 있어도 해당 테스트 단위가 중단되지 않고 끝까지 수행될 수 있도록 assertAll로 테스트 확언문을 감쌌습니다! 감사합니다 😆

2022-06-04 09:52 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
> +@Primary
`@Qualifier` 어노테이션은 스프링 컨테이너가 조건에 맞는 `Bean`을 여러개 찾았을 때 빈을 선택하는 정보를 줄 수 있습니다. 
사용법은 `@Qualifier("name")` 으로 사용할 수 있습니다.

`@Primary` 어노테이션은 단순히 클래스 레벨에 적용해 조건에 맞는 빈들 중 우선순위를 지정해 줄 수 있습니다. 
만약 여러 개의 클래스에 `@Primary` 어노테이션이 적용되어 있다면 유일한 빈을 찾을 수 없다는 에러가 발생하게 됩니다.

2022-06-04 09:55 UTC, who-hoo commented on BE/src/main/resources/sql/schema.sql
> +        REFERENCES room (id) ON DELETE RESTRICT ON UPDATE RESTRICT;
> RESTRICT 가 기본값임에도 불구하고

사실은 몰랐던 사실~~~,,,,!ㅋㅋㅋㅋㅋㅋ 감사합니다ㅎㅎㅎ :stuck_out_tongue_closed_eyes:

2022-06-04 09:58 UTC, who-hoo commented on BE/src/main/resources/sql/schema.sql
> +    `rate`       DECIMAL(3, 2) NOT NULL COMMENT '별점',
너무 좋아요~ 적용하면서 별점 외에도 음수값이 없을 속성들에 `UNSIGNED` 속성 일괄 추가 완료하였습니다 감사합니다! 😆

2022-06-04 10:03 UTC, who-hoo commented on BE/src/main/resources/sql/schema.sql
> +    `type`              VARCHAR(5)  NOT NULL COMMENT '회원타입(G: 일반, H: 호스트)',
db에서 enum 타입을 사용할 경우, enum 타입의 내용 수정 시 자바 코드의 enum과 테이블 변경(alter table)을 둘 다 해주어야해서 기존의 방법보다 작업량이 늘어나게될 것 같습니다.

db에서의 enum타입의 사용은 나쁜것이라고만 생각했는데, 참고 자료 링크를 보니 잘 사용하면 장점도 있을 수 있다는 것을 알게되었네요 감사합니다~

2022-06-04 10:11 UTC, ak2j38 commented on BE/src/main/resources/application.yml
> +    org.hibernate.SQL: debug
`log4j.logger.org.hibernate.type=TRACE` 옵션은 sql에 파라미터를 보기위해 설정하는 옵션인데 단점은 파라미터를 한 눈에 확인하기 어렵다는 점입니다.

저희는 이번 프로젝트에 `p6spy` 라이브러리를 이용하여 파라미터를 확인하고 있습니다!

2022-06-04 10:16 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
>              new MemberResponse(1L, "ahoo", "https://avatars.githubusercontent.com/u/68011320?v=4"),
> `@Profile` 어노테이션을 적용해 테스트때만 적용되도록 수정하겠습니다!

현재 실제 서비스인 `RoomService`가 개발되지 않아 개발이 완료되면 프로파일 별로 나누어서 실행될 수 있도록 변경하겠습니다!

2022-06-04 10:20 UTC, who-hoo commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
클래스 레벨이 아닌 메서드 레벨로 어노테이션 위치 일괄 수정 완료하였습니다!

2022-06-04 10:27 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
> +    private Room room;
읽기 전용으로 수정 완료하였습니다~ 감사합니다 😆

2022-06-04 14:03 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
> +    }
`연관관계 편의 메소드`를 통해 해결했습니다.
결국에는 `setter`지만요.....ㅠㅠ

2022-06-04 14:06 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
> +    private static final WeeklyDiscountChargePolicy instance = new WeeklyDiscountChargePolicy();
`instance`를 말씀하시는게 맞을까요? 약간 instance는 싱글톤으로 구현할 때 자바 개발자들의 암묵적인 약속이라고 생각해서 저렇게 작성하였는데ㅋㅋ 만약에 다른 변수명을 사용하였을때 `getInstance()`라는 메서드명도 같이 변경해주나요?

2022-06-04 14:18 UTC, ak2j38 commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    @OneToMany(mappedBy = "room", cascade = CascadeType.REMOVE, orphanRemoval = true)
변경감지에서 `PERSIST` 옵션은 자식에 연쇄적으로 `persist operation`을 발생시킵니다. 
연쇄적으로 발생한 `persist operation`들은 의도하지 않은 동작들을 일으킵니다.
즉, 트랜잭션이 끝나고 `flush`될 때 자식들에 대해 다시 `persist operation`을 수행하며 원하지 않은 동작들까지 실행합니다.

2022-06-04 14:24 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/entity/Room.java
> +    @OneToMany(mappedBy = "room", cascade = CascadeType.REMOVE, orphanRemoval = true)
CascadeType의 종류
- JPA CascadeType
    - ALL : 모두 적용(상위 엔티티에서 하위 엔티티로 모든 작업을 전파)
    - PERSIST : 영속(하위 엔티티까지 영속성 전달(상위 엔티티를 저장하면, 하위 엔티티도 저장)
    - MERGE : 병합(하위 엔티티까지 병합 작업을 지속)
    - REMOVE : 삭제(하위 엔티티까지 제거 작업을 지속)
    - REFRESH : 새로고침(데이터베이스로부터 인스턴스 값을 다시 읽어올 때, 연결된 하위 엔티티까지 함께 새로고침)
    - DETACH : 영속성 제거(영속성 컨텍스트에서 엔티티를 제거할 때, 연결된 하위 엔티티까지 함께 제거)
- Hibernate CascadeType(Hibernate에서는 JPA CascadeType 외에 세가지 추가로 제공합니다(org.hibernate.annotations.CascadeType))
    - REPLICATE : 복제(상위 엔티티에서 복제 작업을 수행할 때마다 동기화 작업이 하위엔티티에도 전파)
    - SAVE_UPDATE : 연결된 하위 엔티티에 동일한 작업을 전파(save, update, saveOrUpdate와 같은 특정 작업을 할 때 유용)
    - LOCK : 엔티티와 관련된 자식 엔티티를 영속성 컨텍스트에 다시 연결

[참고자료 - jpa cascade types](https://www.baeldung.com/jpa-cascade-types)

2022-06-04 15:20 UTC, ak2j38 commented on BE/src/test/java/com/ahoo/airbnb/data/TestData.java
> +    static {
`CommandLineRunner`를 학습해보았는데 저희의 프로젝트에 적용했을 때의 장점은 동적으로 커맨드라인을 통해 입력받은 값을 초기화 작업에 이용할 수 있고 데이터를 json형태로 받을 수 있다는 점인데 이러한 장점이 저희 프로젝트에 도움이 되는지 잘 모르겠습니다..... 

저희가 놓친 장점이 있을까요?

2022-06-04 16:00 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
> +    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.getInstance(), AccommodationTaxChargePolicy.displayName());
```java
public enum ChargePolicyType {

    ACCOMMODATION("숙박요금정책", AccommodationChargePolicy.displayName()),
    WEEKLY_DISCOUNT("주단위할인정책", WeeklyDiscountChargePolicy.displayName()),
    SERVICE("서비스요금정책", ServiceChargePolicy.displayName()),
    CLEANING("청소비요금정책", CleaningChargePolicy.displayName()),
    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.displayName());

    private String policyName;
    private ChargePolicy chargePolicy;
    private String displayName;

    ChargePolicyType(String policyName, String displayName) {
        this.policyName = policyName;
        this.displayName = displayName;
    }

    public String getPolicyName() {
        return policyName;
    }

    public ChargePolicy getChargePolicy() {
        return chargePolicy;
    }

    public String getDisplayName() {
        return displayName;
    }

    @Component
    @RequiredArgsConstructor
    public static class ChargePolicyInjector {

        private final AccommodationChargePolicy accommodationChargePolicy;
        private final AccommodationTaxChargePolicy accommodationTaxChargePolicy;
        private final CleaningChargePolicy cleaningChargePolicy;
        private final ServiceChargePolicy serviceChargePolicy;
        private final WeeklyDiscountChargePolicy weeklyDiscountChargePolicy;

        @PostConstruct
        public void postConstruct() {
            ACCOMMODATION.chargePolicy = accommodationChargePolicy;
            WEEKLY_DISCOUNT.chargePolicy = weeklyDiscountChargePolicy;
            SERVICE.chargePolicy = serviceChargePolicy;
            CLEANING.chargePolicy = cleaningChargePolicy;
            ACCOMMODATION_TAX.chargePolicy = accommodationTaxChargePolicy;
        }
    }
}
```

스프링이 관리해주는 싱글톤 방식을 적용해 보았습니다. 구현체 주입을 스프링이 책임지다보니, 테스트 코드를 작성할 때 스프링에 대한 의존성이 생겨버리는데, 모든 구현체의 Mock 객체를 만들어줘야할까요?ㅠ_ㅠ

2022-06-04 16:26 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
> +    List<ChargePolicyType> findActiveChargePolicyTypeById(Long id);
```java
//        기존 코드
//        List<ChargePolicyType> roomChargePolicies =
//            roomRepository.findActiveChargePolicyTypeById(roomId);

        List<ChargePolicyType> roomChargePolicies = room.getRoomChargePolicies().stream()
            .filter(p -> p.getChargePolicy().getIsActive())
            .map(rcp -> rcp.getChargePolicy().getChargePolicyType())
            .collect(Collectors.toList());
```

자바 소스에서 필터링에 도전해보았으나 이것은 아닌것같따 땅땅땅

2022-06-04 16:28 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
> +    public RoomChargeResponse calculateTotalChargeOf(Long roomId, RoomChargeRequest roomChargeRequest) {
의도하신바가 맞는지는 모르겠으나,,, 메서드 분리로 리팩토링 사알짝 해보았습니다~,,ㅎㅎ

2022-06-05 00:37 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
> +    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.getInstance(), AccommodationTaxChargePolicy.displayName());
이런 식으로 적용이 가능할까요?
```java
// AS-IS
public class MyService {

@Autowired
private SomeBean bean;

private String status;

@PostConstruct
private void init() {
    status = someBean.getStatus();
} 
```

```java
// TO-BE
public class MyServiceTest(){

@InjectMocks
private MyService target;

@Mock
private SomeBean mockBean;

@Before
public void setUp() throws NoSuchMethodException,  InvocationTargetException, IllegalAccessException {

    MockitoAnnotations.initMocks(this);

    when(mockBean.getStatus()).thenReturn("http://test");

    //call post-constructor
    Method postConstruct =  MyService.class.getDeclaredMethod("init",null); // methodName,parameters
    postConstruct.setAccessible(true);
    postConstruct.invoke(target);
  }

}
```

2022-06-05 07:16 UTC, sigridjineth commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
메소드 레벨에서 선언된 `@Transactional` 이 클래스 레벨에서 선언된 `@Transactional` 보다 우선합니다.
```java
@Transactional(readOnly = true)
public class DefaultFooService implements FooService {

  public Foo getFoo(String fooName) {
    // do something
  }

  // these settings have precedence for this method
  @Transactional(readOnly = false, propagation = Propagation.REQUIRES_NEW)
  public void updateFoo(Foo foo) {
    // do something
  }
}
```

2022-06-05 07:19 UTC, sigridjineth commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
메소드에 `@Transactional` 이 있으면 클래스 레벨의 선언보다 우선하여 적용이 되는데요. 우선순위는 클래스의 메소드, 클래스, 인터페이스의 메소드, 인터페이스 순으로 부여됩니다. 인터페이스 레벨에 부여된 `@Transactional` 은 default 트랜잭션 속성을 가져서 읽기 전용 속성이 `false` 가 되어요. 즉, 모든 메소드에 적용이 되겠지요. 하지만 특정 메소드에서 메소드 레벨의 트랜잭션 선언이 되어 있다면, 만약 그 선언이 읽기 전용 속성이 true라면, 인터페이스 레벨의 선언보다 우선해서 적용될 것이에요.

타입 레벨과 메소드 레벨에 동시에 @Transactional이 적용하지 말고, 하나의 규칙을 정해서 일관성 있게 가져가면 좋은데요. 저라면 메소드 레벨에 모두 선언하는 것이 더욱 명시적이라고 생각합니다. 또한, 인터페이스와 클래스 양쪽에 불규칙하게 @Transactional이 혼용되는 건 바람직하지 못합니다. 왜 인터페이스와 클래스 양쪽에 선언하는 것의 동작이 다를까요? 이를 학습하려면 프록시에 대한 이해가 필요합니다.

[참고할 만한 링크](https://stackoverflow.com/questions/23132822/what-is-the-difference-between-defining-transactional-on-class-vs-method)

2022-06-05 08:31 UTC, sigridjineth commented on BE/src/test/java/com/ahoo/airbnb/data/TestData.java
> +    static {
그렇군요, 테스트용 더미 데이터를 프로젝트 실행 초기에 로드할 수 있을 것이라는 지점에서 학습 추천을 드렸던 것입니다.

2022-06-05 08:32 UTC, sigridjineth commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
> +    private static final WeeklyDiscountChargePolicy instance = new WeeklyDiscountChargePolicy();
흠, 저는 instance라고 해서 무엇에 대한 인스턴스를 이야기하는거지? 라고 생각했는데요. `policy` 라는 사실이 더욱 구체적으로 명시되면 좋겠습니다.

2022-06-05 08:33 UTC, sigridjineth commented
수고 많으셨습니다. 대략적으로 논의가 종료되었다고 생각하여 이만 머지하겠습니다.

2022-06-05 08:33 UTC, merged

2022-06-05 15:15 UTC, who-hoo commented on BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
> +    ACCOMMODATION_TAX("숙박세요금정책", AccommodationTaxChargePolicy.getInstance(), AccommodationTaxChargePolicy.displayName());
저는 아직 리플렉션을 잘 몰라서..ㅎㅎ 일단 참고만 하겠습니다

테스트에서 리플렉션을 쓰는게 안좋을것같은 느낌인데,,,
1. 그냥 셀프 구현 싱글톤 사용
2. 스프링부트테스트로 테스트
3. 리플렉션 사용

이렇게 있다고 하면,,, 저는 약간 1-2-3순으로 좋은 것 같아요
(@ak2j38 : 1번을 잘 구현했다면 1-2-3, 잘 구현 못했다면 2-1-3)

2022-06-05 15:21 UTC, who-hoo commented on BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
> +@Transactional
일단 북마크 해두고 강해져서 돌아오기.... 👀 
- https://docs.spring.io/spring-framework/docs/5.1.8.RELEASE/spring-framework-reference/data-access.html#transaction-declarative-annotations
- https://docs.spring.io/spring-framework/docs/3.0.x/spring-framework-reference/html/transaction.html