[Team-05][BE] 비씨 & 노리 airbnb 프로젝트 2주차 두 번째 PR
codesquad-members-2022/airbnb pull request #182
Opened 2022-06-03 02:55 UTC by honeySleepr

안녕하세요 단! 노리 & BC입니다

2 주차 두 번째 PR 드립니다. 
단이 리뷰하기 힘드실까 봐 코드를 많이 안 짰습니다!..는 아니고 학습이랑 병행하다 보니 이렇게 되었습니다 ㅎㅎ😅

## 📝  진행 상황
- wish 등록, 삭제 기능 구현
- wishlist에 추가한 숙소의 상세정보 조회 기능 구현 
- 검색 기능을 드디어 만들기 시작했으나 JPQL로는 쿼리를 만들 자신이 없어서 Querydsl 학습 시작;
- DataProcessor를 이용해 만들어 더미데이터 초기화용 data.sql 파일 작성

2022-06-03 14:59 UTC, Hyune-c requested changes
수고하셨습니다.

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/BnbController.java
> +}
뭔가 무의미한 개행이 많네요..
이 클래스는 미구현이라고 간주하고 넘어가겠습니다.

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/BnbService.java
> +	}
미구현이 꽤 많네요. todo를 달아주세요.

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/BnbService.java
> +	}
조회성 메서드임에도 `@Transactional`이 그대로 걸리는 것 같습니다.

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/bnb/dto/SearchQueryDto.java
> +	private LocalDate checkOut;
NotBlank를 string이 아닌 타입에 쓰는건 처음 봤는데, 의도하신 건가요?

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/main/java/project/airbnb/reservation/DetailReservationDto.java
> +public class DetailReservationDto {
네이밍에 대해서도 좀 더 고민해보면 좋을 것 같습니다.
개인적으로는 대상을 앞에 두는 것을 선호해요.

만약 지금의 네이밍이라면 Detail이라고 쳤을 때 자동 완성 어시스트 되는 클래스가 너무 많을 것 같아요.
반대로 Reservation이 앞이라면 어시스트 되는 대상이 줄겠죠.

2022-06-03 14:59 UTC, Hyune-c commented on Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
setup이 반복되네요.
일정 수준 이상이 되면 분리하는 것을 추천합니다.

2022-06-04 15:14 UTC, honeySleepr commented on Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
>  	}
> setup이 반복되네요. 일정 수준 이상이 되면 분리하는 것을 추천합니다.
https://github.com/codesquad-members-2022/airbnb/pull/182#discussion_r889026199

이런 식으로 수정하는 건 어떨까요?

2022-06-04 15:14 UTC, nohriter commented on Backend/src/main/java/project/airbnb/bnb/BnbController.java
> +}
다음에는 더 꼼꼼하게 살펴서 올리도록 하겠습니다. 🫡

2022-06-04 15:14 UTC, nohriter commented on Backend/src/main/java/project/airbnb/bnb/BnbService.java
> +	}
readOnly 옵션을 붙이도록 하겠습니다!

2022-06-04 15:14 UTC, nohriter commented on Backend/src/main/java/project/airbnb/bnb/BnbService.java
> +	}
미구현 코드에는 todo를 붙이도록 하겠습니다!!

2022-06-04 15:14 UTC, nohriter commented on Backend/src/main/java/project/airbnb/bnb/dto/SearchQueryDto.java
> +	private LocalDate checkOut;
빠르게 학습하고 적용해 보았는데 잘못 알고 적용한 것 같습니다! 수정하겠습니다!!

2022-06-04 15:15 UTC, nohriter commented on Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
https://github.com/codesquad-members-2022/airbnb/pull/182#discussion_r889568288

2022-06-04 20:35 UTC, Hyune-c commented on Backend/src/test/java/project/airbnb/reservation/ReservationControllerTest.java
>  	}
네. 저렇게 묶는 방법도 있고, 더 나아가면 테스트 픽스처를 만들 수도 있습니다.

https://naver.github.io/fixture-monkey/kr/

2022-06-04 20:36 UTC, Hyune-c approved these changes
수고하셨습니다.

2022-06-05 08:54 UTC, merged