[Team-20 BE] Airbnb 프로젝트 3주차(수요일) 리뷰 요청
codesquad-members-2022/airbnb pull request #232
Opened 2022-06-07 19:28 UTC by ikjo93

안녕하세요~ Dan~!! 지난 황금연휴(6/4~6/6)는 잘 보내셨나요? 벌써 이번 Airbnb 프로젝트도 마무리가 다 되어 가네요 😂

이번 PR 내용은 일요일부터 화요일까지 진행했었던 내용들에 해당되며 작업했던 내용들은 README 파일에 작성해 보았습니다. 특히, 처음으로 이번에 JWT를 통한 로그인 검증 로직을 프로그래밍 해볼 수 있었는데, 아직 부족한 점이 많습니다. 😂 그리고 이번 PR 이후로는 기능 구현 작업은 마무리하고 프론트 엔드와 연동하면서 발생할(?) 오류들을 잡는데 시간을 많이 사용할 것 같습니다. 🤣

이번 PR도 잘 부탁드립니다 Dan~

2022-06-07 19:45 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/interceptor/AuthInterceptor.java
> +        }
`/api/accommodations` 이라는 URL로 GET 요청과 POST 요청 2개의 API가 존재하는데 현재 로그인 검증을 하기 위한 요청은 POST 요청(숙소 예약 API)이므로 나머지 요청은 걸러내고자(그대로 통과) 했습니다.

2022-06-07 19:51 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/jwt/JwtManager.java
> +        valueOperations.set(accessToken, JwtConstant.LOGOUT_FLAG, Duration.ofMillis(expireTime));
+ 로그아웃 요청 시 레디스(redis)에 access token 값이 key값으로, 지속 시간은 현재 access token의 남은 만료 시간으로 저장하도록 했습니다.
+ 이는 로그아웃 처리 이후로 아직 만료 시간이 남은 해당 access token를 무효화 시키고자 함이었습니다.
+ 로그인 검증 시 해당 access token 값이 레디스에 존재하는 경우 로그아웃 처리된 것으로 간주

2022-06-07 19:57 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/jwt/JwtConstant.java
> +    public static final long REFRESH_TOKEN_DURATION = 60 * 2 * 1000; // refresh token 유효시간 : 2분
액세스 토큰과 리프레쉬 토큰의 만료 기한은 테스트를 위해(만료 확인) 편의상 짧은 시간으로 설정해놓았습니다.

2022-06-07 19:58 UTC, ikjo93 commented on be/README.md
> +> ![image](https://user-images.githubusercontent.com/82401504/172468079-244b8df4-3464-49f1-8649-b454028d9101.png)
현재까지 작업한 인프라의 구성 현황입니다.

2022-06-07 20:23 UTC, ikjo93 commented on be/README.md
> + - 클라이언트가 보낸 access token에 대한 정보를 레디스에 저장(블랙 리스트)하는데, 이때 해당 데이터의 만료 시간은 해당 access token의 남은 만료 시간으로 설정
이번 PR에서 구현한 JWT 활용 로그인 검증 흐름에 대한 예시입니다.

2022-06-09 07:56 UTC, ikjo93 commented
아직 리뷰 주시기 전이라 몇가지 소소하게 수정 부분이 있어 수정 커밋 올렸습니다. 😀

2022-06-09 14:52 UTC, Hyune-c requested changes
수고하셨습니다. 
많은 공부가 될 주제인 JWT를 잘 구현해주셨네요.
조금 아쉬운 것은 JWT를 string으로 활용하고 있다는 점입니다.

- accessToken, refreshToken을 객체로 사용한다면 어떨까요?
    - 아마 생성하는 provider나 validator하는 과정을 모을 수 있을 것 입니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/README.md
> + - 클라이언트가 보낸 access token에 대한 정보를 레디스에 저장(블랙 리스트)하는데, 이때 해당 데이터의 만료 시간은 해당 access token의 남은 만료 시간으로 설정
이것을 글이 아닌 그림으로 그려주시면 어필하기 더 좋을 것 같아요.

2022-06-09 14:52 UTC, Hyune-c commented on be/README.md
> + - 클라이언트가 보낸 access token에 대한 정보를 레디스에 저장(블랙 리스트)하는데, 이때 해당 데이터의 만료 시간은 해당 access token의 남은 만료 시간으로 설정
jwt를 쓰지만 redis에 관리도 하는 jwt-session의 혼합 형태이네요.
jwt의 장점인 `서버의 자원을 사용하지 않는다.` 를 포기하면서 지금의 형태를 구성하신 이유가 궁금합니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/jwt/JwtConstant.java
> +    public static final long REFRESH_TOKEN_DURATION = 60 * 2 * 1000; // refresh token 유효시간 : 2분
test를 위해서라면 만료시간이 짧은 토큰을 생성하는 API를 별도로 만들어 줄 수 있습니다.
백도어 API 라고 표현하기도 하고 보통 보안 취약점이라 안좋은 방법이라고 하기도 하는데, prod 환경에서는 접근하지 못하게 막는다면 괜찮다고 생각합니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/config/MvcConfig.java
> +            .addPathPatterns("/api/accommodations");
`nit` 보통 대부분의 API는 인증이 필요하고, 소수의 API만 인증이 필요하지 않기에 `excludePathPatterns`을 더 자주 썻던 것 같습니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/controller/AccommodationController.java
> +    }
`nit` `RestController`를 사용한다면 ResponseEntity도 생략하는 것이 좋다고 생각합니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/service/TokenService.java
> +    }
토큰 생성과 redis 저장이라는 2개의 행위가 하나의 메서드에서 이루어지고 있네요!

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/jwt/JwtUtil.java
> +public class JwtUtil {
`nit` 유틸리티 클래스는 객체화를 막기 위해 private 생성자를 두기는 것을 추천합니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/controller/AuthController.java
> +        response.addCookie(createCookieWithRefreshToken(loginResponse.getRefreshToken()));
`nit`
header를 조작하지 않으시면 좀 더 깔끔한 코드가 될 것 같아요.
body로 token이 반환되는 카카오 로그인 API를 첨부합니다.

https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/controller/ExceptionController.java
> +    }
`NoSuchElementException`은 403과 잘 연결되지 않는 느낌입니다.

2022-06-09 14:52 UTC, Hyune-c commented on be/src/main/java/codesquad/airbnb/jwt/JwtManager.java
> +        valueOperations.set(accessToken, JwtConstant.LOGOUT_FLAG, Duration.ofMillis(expireTime));
- PC에서 로그아웃하면 앱에서도 로그아웃 되어야 하는가?

업무 요건에 따라 다르게 구현하실 수 있을 것 같아요.
지금도 괜찮습니다.

2022-06-09 15:49 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/jwt/JwtConstant.java
> +    public static final long REFRESH_TOKEN_DURATION = 60 * 2 * 1000; // refresh token 유효시간 : 2분
오 백도어 API는 처음들어봅니다 ㅎㅎ 이번에 키워드를 알았으니 다음 프로젝트를 할 때 좀 더 알아보겠습니다 🙏

2022-06-09 17:16 UTC, ikjo93 commented on be/README.md
> + - 클라이언트가 보낸 access token에 대한 정보를 레디스에 저장(블랙 리스트)하는데, 이때 해당 데이터의 만료 시간은 해당 access token의 남은 만료 시간으로 설정
더 많고 깊은 이유가 있겠지만 이번에 처음으로 JWT를 학습해보면서 배운 것들을 토대로 답변드려보고자 합니다 🙏

+ 질문 : `jwt의 장점인 "서버의 자원을 사용하지 않는다"를 포기하면서 "지금의 형태"를 구성한 이유`

+ 1️⃣ 인터넷 서칭을 통해 학습한 내용을 기반으로 한 답변
  + jwt의 경우 token을 어떤 해커(?)에게 탈취당한 경우 나쁜X가 이를 악용할 수도 있는데, 이를  무효화할 방법이 없다는 문제가 있습니다.
  + 이러한 문제점을 해결하기 위해 토큰을 access token과 refresh token으로 나누고 access token은 유효 시간을 짧게 두고, refresh token은 유효 시간을 상대적으로 길게 두는 방법이 있습니다.
  + 이때 해커가 access token을 탈취하더라도 access token은 유효 시간이 짧기 때문에 피해를 줄일 수 있기(차선책 느낌?) 때문입니다.
    + 하지만 이런 구조로도 `이 짧은 시간 동안에 발생하는 피해`는 막을 수 없기에 뭔가 다른 방법이 필요한 것 같습니다. 💦 이 부분에 있어서 답변을 드릴려면 좀 더 학습과 경험이 필요할 것 같습니다..😂
  + 아무쪼록 access token의 유효 시간이 짧기에 사용자가 로그인을 빈번하게 하는 불편함을 개선코자 refresh token이라는 것을 서버에 저장(여기서는 redis)하고 이를 클라이언트가 보낸 refresh token과 검증하여 클라이언트에 access token을 새로 발급해주는 것입니다.
    + refresh token의 유효 시간도 지나면 사용자에 재로그인을 요청합니다.
    + redis의 경우 인메모리 저장 방식으로 하드디스크 I/O 대비 빠른 속도로 접근할 수 있습니다.
    + `refresh token도 탈취당하면 어떻할까?`라는 질문도 있을 수 있을 거 같은데 이 부분에 있어서도 좀 더 학습과 경험이 필요할 것 같습니다..🤣

+ 2️⃣ 개인적으로 생각해본 이유
  + 우선 당장 로그아웃이라는 기능을 구현해야한다고 생각했을 때 토큰을 관리(저장)해야겠다는 생각을 했습니다. 토큰에는 만료 시간이 있지만 이는 사용자나 서버가 원할 때 무효화하는 방법이 아니기 때문이었습니다. 토큰을 서버에서 관리함으로써 로그아웃 API 통해 사용자가 원할 때 로그아웃을 서버에 요청할 수가 있었습니다.

+ 답변 요약
  + access token의 탈취 당할 경우 피해 최소화
  + 사용자나 서버가 원할 때 토큰 무효화 가능

+ 나의 답변에 대한 의문점과 결론
  + 앞선 이유들을 고려해보면 `어짜피 refresh 토큰을 저장할거면 그냥 세션을 쓰면 안되?` 라는 질문이 나올 수도 있을 거 같습니다. 이에 대해 답변하려면 사실 근본적인 질문인 `왜 jwt를 사용했는가?`에 대한 답변이 선행되어야 할 것 같습니다.
  + 세션은 stateful하여 상태관리가 용이하다는 장점이 있지만 이는 서버에 부하를 키우고 세션 DB 공유 필요 등으로 인해 서버 확장이 어려운 단점이 있습니다. 반면  jwt의 경우 세션과 달리 서버의 자원을 사용하지 않는(백엔드 부하 감소 등) 장점이 있지만 이로 인해 stateless 특성이 있는데 이게 장점(서버 확장 용이)이면서도 단점(탈취 시 보안 우려 등)이 될 수도 있습니다.
  + 이때 jwt의 기존 단점을 보완하는 방식이 refresh token 저장 형태의 방식인 것인데, 이렇게까지 하면서 jwt 방식을 사용하는 데에는 앞서 세션을 사용해서 겪는 문제점(단점) 보다는 더 나은 결과(보안과 기능에 대한 트레이드 오프된 형태로서)이기 때문이지 않을까 싶습니다.
  + 하지만 솔직히 스스로 되돌아 보았을 때는 이번 프로젝트에 이러한 형태의 jwt를 적용한 이유는 `미션 요구사항에 jwt를 사용`하라고 해서 jwt를 사용한거고 access token만을 사용하는 방식에서 좀 더 개선된 형태인거지 `내 서비스에는 session 보다는 이러한 형태의 jwt가 더 적합해!`라고 생각해서 사용한 것은 아닌 것 같습니다.
  + 즉, 근본적으로 `내가 운영하려고 하는 서비스에는 어떠한 방식이 더 적합한가?`에 초점을 두고 고민해봐야 할 필요성을 느꼈습니다.
  + 결론적으로 `어짜피 refresh 토큰을 저장할거면 그냥 세션을 쓰면 안되?` 라는 질문에 대한 답변은 일단은 미루어 두고 충분한 학습과 경험을 더욱 쌓은 뒤에 알아봐야할 것 같습니다.
  + 그래도 이번 프로젝트에 jwt를 적용해봄으로써 jwt의 개념과 특성 그리고 동작 원리 등에 대해 학습해볼 수 있었으니 추후에 프로젝트를 적용할 때는 세션과 jwt 두 개의 방식에 대해 고민할 때는 지금 보다는 좀 더 깊이있는 학습과 경험을 해볼 수 있지 않을까 기대해봅니다..😀

2022-06-09 17:27 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/service/TokenService.java
> +    }
앗 에공.. `메서드가 한 가지 일만 하도록 최대한 작게 만들자.`라는 클린 코딩 관련 내용이 떠올랐습니다..😅

2022-06-09 18:21 UTC, ikjo93 commented on be/src/main/java/codesquad/airbnb/controller/ExceptionController.java
> +    }
NoSuchElementException 보다는 적합하지 않은 인자(여기서는 토큰)를 메소드에 넘겨주었을 때 발생하는 IllegalArgumentException이 적합하다는 생각이 들었고 토큰이 유효하지 않으므로 상태코드는 401 Unauthorized.이 적합하다는 생각이 들었습니다!

2022-06-09 18:34 UTC, ikjo93 commented
단!! 오늘도 정성스러운 리뷰에 감사드려요!! 덕분에 좋은 키워드들과 더 나은 방향성에 대해 고민해볼 수 있을 것 같습니다!! 😁 일단은 가벼운 내용들을 위주로 수정 작업하였고 다음 PR에서 Access Token을 객체 타입으로 바꿔보는 작업에 도전해보고자 합니다!! 🙏

2022-06-10 12:47 UTC, ikjo93 commented on be/README.md
> + - 클라이언트가 보낸 access token에 대한 정보를 레디스에 저장(블랙 리스트)하는데, 이때 해당 데이터의 만료 시간은 해당 access token의 남은 만료 시간으로 설정
> 이것을 글이 아닌 그림으로 그려주시면 어필하기 더 좋을 것 같아요.

어제 주셨던 이 리뷰가 생각나서 나름대로 그림으로 그려보고 블로그에 올려봤습니다. 😁
https://ikjo.tistory.com/255

2022-06-10 12:50 UTC, merged