[Team-14 BE] airbnb 프로젝트 3주차 1번째 PR입니다.
codesquad-members-2022/airbnb pull request #252
Opened 2022-06-08 08:17 UTC by naneun

## 3주 1차 PR 요청
안녕하세요! brian
team-14 에서 백엔드를 담당한 로니와 리아코입니다!

## 한 일
- Json Parsing 관련 리펙토링 작업
- QueryDSL 을 사용하여 숙소 검색 API 구현
- 중부원점좌표를 위도, 경도로 변환하는 작업
- 더미 데이터 추가 입력 작업 진행
- 간단한 예외처리 구현

---------

감사합니다!

2022-06-09 22:43 UTC, wheejuni requested changes
수고 많으셨습니다~
몇 가지 리뷰 남겨드립니다. 확인 부탁드려요

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/application/LoginService.java
> +        return jwtProvider.generateToken(userInfo.getGithubId());
음 저장은 아닌 것 같군요.
여기서 레포지토리를 주입받지 않으신 이유는 있을까요?

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +    }
`@Builder` 는 사용해 보셨을까요?

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/github/GithubToken.java
> +    private String tokenType;
모든 곳에서 이렇게 언더스코어로 변환되어야 한다면, `Jackson` 설정을 통해 전역적으로 설정을 부어줄 수 있는 인터페이스가 있습니다.
한번 찾아보시고 적용해 보시면 좋아요.

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/github/GithubTokenRequest.java
> +@AllArgsConstructor
`@NoArgs` 는 여기는 불필요한가보군요.

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/ui/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
`Interceptor` 보단 Spring Security쪽 로직을 사용해야 할 것으로 보이긴 합니다~
지금 방식이 나쁜 건 아닌데, 실제 로직에서 사용자 인증 정보를 사용할 필요가 있을때 어떻게 구현하실지 궁금합니다.

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/ui/LoginController.java
> +public class LoginController {
로그인은 가급적 컨트롤러 진입 전 처리되게 하는 방향이 좋기는 합니다. 그러기 위해선 어떤 구현을 가져가야 할지도 고민해주세요~

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/common/config/WebConfig.java
> +    }
`WebConfig` 이라는 클래스명과는 좀 안맞는 위치인 것 같습니다. ㅎㅎ

2022-06-09 22:43 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/room/application/RoomService.java
> +        return new PageImpl<>(roomCardResponses, pageable, rooms.getTotalElements());
굳이 꺼내서 다시 집어넣고 하지 않아도 됩니다.
https://stackoverflow.com/questions/39036771/how-to-map-pageobjectentity-to-pageobjectdto-in-spring-data-rest

2022-06-10 04:42 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +    }
생성자를 직접 작성하고 @Builder 을 붙여 사용해봤었는데, 정적 팩토리 메서드 작성시 필드가 많아질수록 클래스 라인수가 길어져 간단하게 @AllArgsConstructor 만을 사용하여 작성해봤습니다! 지금보니 @Builder 를 사용하는 것이 라인수가 많아지더라도 안정성 및 가독성을 위해 좋을 것 같습니다! 😅

2022-06-10 04:44 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/auth/application/LoginService.java
> +        return jwtProvider.generateToken(userInfo.getGithubId());
클라이언트와 로그인 기능까지는 맞춰보지 못할 것 같아 간단하게 틀만 상기하며 작성해봤습니다! 😅

2022-06-10 04:51 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/auth/github/GithubTokenRequest.java
> +@AllArgsConstructor
엑세스 토큰 요청 시 저희가 설정해야할 파라미터를 담은 Dto 이기 때문에 @AllArgsConstructor 만 작성해놓아도 충분했었습니다 😄

2022-06-10 04:52 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/common/config/WebConfig.java
> +    }
JpaConfig 클래스에 포함되도록 변경했습니다 ㅎㅎ 감사합니다~

2022-06-10 04:58 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/room/application/RoomService.java
> +        return new PageImpl<>(roomCardResponses, pageable, rooms.getTotalElements());
감사합니다! 😄 보내주신 링크를 참고하여 간단하게 작성할 수 있었습니다!

2022-06-10 05:08 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/auth/ui/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
Spring Security 로직을 참고하여 해당 로직들을 Interceptor -> filter 로 이동시켰습니다! 실제 작성해보고자했던 로직은 Interceptor 에서 MemberRepository 를 주입 받아 Jwt 토큰에 담긴 인증정보를 사용하여 레포지토리에서 Member 객체를 반환받은 뒤 request attribute 에 저장하고 이를 필요한 API 에서 꺼내 사용하려고 했었습니다! 😄

2022-06-10 05:17 UTC, CMSSKKK commented on backend/src/main/java/com/team14/cherrybnb/auth/github/GithubToken.java
> +    private String tokenType;
모든 곳에 언더스코어를 적용하는 방법(같은 네이밍전략을 적용)을 찾아보면서, 3가지 방법을 찾았습니다. 

1. properties에 namingStrategy를 snake case로 두는 방법 `spring.jackson.property-naming-strategy=SNAKE_CASE`
2. `@JsonTypeInfo` 어노테이션을 활용하는 방법  https://stackoverflow.com/questions/19379863/how-to-deserialize-interface-fields-using-jacksons-objectmapper
3. `ObjectMapper`를 설정해서 bean으로 등록하는 방법 3가지를 찾을 수 있었습니다.

인터페이스를 말씀해주셔서 그 의미에 맞게 검색을 많이 해봤으나,  3가지 방법 중 어떤 방식을 뜻하셨는지 파악하지 못했습니다. 

위 방법들이 아니라면 조금만 더 자세하게 키워드 알려주시면 감사하겠습니다!

2022-07-11 07:46 UTC, merged