[team-07] sally + zzangmin 3주차 첫번째 PR
codesquad-members-2022/airbnb pull request #257
Opened 2022-06-08 08:25 UTC by leezzangmin

안녕하세요 roach! 
리뷰해주셔서 감사합니다!

*진행상황
- github oauth + JWT
- 예약하기 계산 로직 리팩토링, 지역 검색어 기반 검색 요청

2022-06-08 12:02 UTC, tmdgusya requested changes
전반적으로 코드는 깔끔해지는것 같아요 계속! 좋습니다!

다만 Object 사용에 대한 부분을 한번 더 생각해보셨으면 좋겠어요. 꼭 사용해야만 하는 부분인가요?

2022-06-08 12:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/authentification/OauthController.java
> +        Map<String, String> userAttributes = oauthService.getUserAttributes(accessToken);
이렇게 받는 것보다 DTO 를 귀찮더라도 만드시는걸 추천드려요.
저는 Type 언어에서는 최대한 Schema 를 만들어서 쓰는게 좋다고 생각해요. 오류 발견도 런타임 시점이 아닌 컴파일 시점으로 옮겨질 수 있으니까요?

2022-06-08 12:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/config/AppConfiguration.java
> +	}
Bean 으로 구성하셨군요 👍

2022-06-08 12:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchDto.java
> +				(String)request.get(LOCATION.getText()),
꼭 Object 로 받는 이유가 있나요?

2022-06-08 12:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchApiController.java
> +	public ResponseEntity<SearchDto.RoomsResponse> searchRegion(@RequestParam HashMap<String, Object> request) {
Type 을 이용안하시는 이유가 있나요?

2022-06-08 12:02 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchRoomDto.java
> +	@QueryProjection
👍 좋아요

2022-06-09 07:03 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchDto.java
> +				(String)request.get(LOCATION.getText()),
생각대로 안돼서 삽질을 좀 했던 부분이었습니다. ㅎㅎ
@GetMapping에 @ResponseBody 로 안 되어서(제 팀원 짱민은 되시고....) 
ObjectMapper 로 자동 변환 등.. 쉽게 잘 안되어서 (JavaType으로 변환시켜서... 하는거 같았는데..)

삽질을 하다가 별 생각 없이 작업을 하게 된 것 같아요. ㅎㅎ

2022-06-09 07:09 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchApiController.java
> +	public ResponseEntity<SearchDto.RoomsResponse> searchRegion(@RequestParam HashMap<String, Object> request) {
``` java
(@Valid @RequestBody SearchDto.LocationRequest request) { }
```
요청을 전혀 안 받고, 에러도 안 뜨고 이유를 모르겠어서 Map으로 변경하니, 들어와져서 dto로 작업을 못했습니다.
근데.. 저희 팀원분은 되신가도 해서.. 모르겠어요. 🙃

2022-06-09 07:10 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchRoomDto.java
> +	@QueryProjection
이번에 Querydsl 처음 써봐서 ㅎㅎ 다행입니다 .
감사합니다~

2022-06-09 12:23 UTC, tmdgusya commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchApiController.java
> +	public ResponseEntity<SearchDto.RoomsResponse> searchRegion(@RequestParam HashMap<String, Object> request) {
아하 그렇군요 흐음 이유를 찾아보면 좋긴한데 일단 안된다면 시간관계상 Map 을 사용하시는것도 나쁘지 않을것 같아요. 나중에 한번 탐구해보시죠 ㅎㅎ

2022-06-09 12:23 UTC, tmdgusya commented
고생하셨어요 머지해드리겠습니다.

2022-06-09 12:23 UTC, merged

2022-06-10 05:02 UTC, sally-ksh commented on BE/airbnb/src/main/java/team07/airbnb/search/SearchApiController.java
> +	public ResponseEntity<SearchDto.RoomsResponse> searchRegion(@RequestParam HashMap<String, Object> request) {
ㅠㅠ