[Team-16][BE] airbnb 프로젝트 PR #1
codesquad-members-2022/airbnb pull request #29
Opened 2022-05-25 08:13 UTC by dongkyu-park

안녕하세요. team-16 be 구현을 맡게 된 헤이호 입니다.

fe 분들과 요구사항을 살펴보며 각자 분야에서 구현해야 할 부분에 대한 논의하는 작업을 했습니다.
처음 접하는 개념과 기술들이 많아 우선 검색 기능 구현에 중점을 두고 위시리스트, 로그인 등의 기능은 뒤쪽으로 미뤄 두었어요.

기능을 구현한 부분은 없지만, 다음 PR에 초기설정 코드까지 뭉쳐 올리게 되면 변경된 라인이 길어질 것 같아서
프로젝트 초기 설정 및 jpa 연관관계를 매핑한 간략한 엔티티 구조를 만들고 1차적으로 PR 요청 드립니다.

3주간 잘 부탁드립니다😊

2022-05-25 14:06 UTC, tmdgusya requested changes
JPA 사용과 배포 미션때문에 어렵게 느껴지실수도 있지만, 두분이서 같이 공부하시고 공유하면서 진행하시면 잘 진행하실수 있을거에요~! 화이팅입니다.

몇가지 부분 수정만 하고 넘어가시죠~!

2022-05-25 14:06 UTC, tmdgusya commented on be/src/main/java/kr/codesquad/airbnb/domain/Booking.java
> +    private Guest guest;
`@Embedded` 좋네요.

2022-05-25 14:06 UTC, tmdgusya commented on be/src/main/java/kr/codesquad/airbnb/domain/Booking.java
> +@Setter
무분별하게 사용하는건 금지해주세요~

조영호님 특강에서도 들었듯이, 외부에 열어주어야 하는 인터페이스만 생성해주세요.
예를 들면 Booking 의 경우 예약함수나 예약정보를 보여주는 메소드가 필요하겠죠?

2022-05-25 14:06 UTC, tmdgusya commented on be/src/main/java/kr/codesquad/airbnb/domain/Discount.java
> +public class Discount {
Discount 는 할인 정보 테이블인가요? 
room 과 discount_id 만으로 할인정보에 대한 표현이 가능한가요?

2022-05-25 14:06 UTC, tmdgusya commented on be/src/main/java/kr/codesquad/airbnb/domain/Room.java
> +    private List<Tax> taxes = new ArrayList<>();
`@OneToMany` 의 경우에는 기본적으로 fetchType 을 Lazy 로 걸고 쓰시는게 좋아요. 만약 Lazy 가 아니라면 현재 Room 을 가져올때 필요하지 않은 상황에도 3개 모두 Discount, Tax, Booking 등을 아무 이유 없이 불러올꺼에요.

왜 아래처럼 default 연관관계를 JPA 에서 이렇게 정의했는지도 공부해보세요.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/57784077/170281410-c41e2a91-00c7-4169-9c43-1d8177386366.png">

2022-05-25 15:23 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/airbnb/domain/Discount.java
> +public class Discount {
앗.. 숙소 데이터 크롤링 해보려고 삽질하구 있는데
데이터 살펴보면서 모자라는 부분들이 보여서 방금 수정 했어요!

2022-05-25 16:00 UTC, dongkyu-park commented on be/src/main/java/kr/codesquad/airbnb/domain/Room.java
> +    private List<Tax> taxes = new ArrayList<>();
> @OneToMany 의 경우에는 기본적으로 fetchType 을 Lazy 로 걸고 쓰시는게 좋아요.

1. fetch 옵션의 기본값이 Lazy 라도, 어노테이션의 속성값으로 명시적으로 입력 해주는게 좋다는 의미가 맞을까요?
 
2. 던져주신 키워드를 보고 학습해 보았습니다.

`@ManyToOne`, `@OneToOne` 의 경우 fetchType 이 Eager 라면, join 쿼리 1번으로 `One` 에 해당하는 필드 값을 가져와서 들고 있지만, 

Lazy 로 설정하게 되면, 필드값을 조회할 때 select문이 추가로 여러 번 발생해 N+1 문제가 발생할 수 있기 때문이고

`@OneToMany` 의 경우 말씀 해주신 내용처럼 필요하지 않은 상황에도 select문을 추가로 발생시켜 조회하기 때문 입니다. fetchType 을 Lazy 로 설정한다면, 로직에서 필요한 경우에만 조회 쿼리를 날리기 때문에 불필요한 데이터 조회를 막을 수 있습니다.

2022-05-26 15:15 UTC, tmdgusya commented on be/src/main/java/kr/codesquad/airbnb/domain/Room.java
> +    private List<Tax> taxes = new ArrayList<>();
1. 아하 fetch 기본 타입이 Lazy 인걸 알고 계셨군요~! 네네 알고 계신다면 명시적으로 적어주지 않아도 될것 같아요.
2. N+1 문제도 왜 발생하는지 잘 생각해보시면 좋을것 같아요. 왜 쿼리가 객체의 값을 평가하는 순간 나갈까요? 어떻게 가능할까요?

2022-05-26 15:15 UTC, merged