[team-21] 데이먼 첫 번째 PR 드립니다.
codesquad-members-2022/airbnb pull request #44
Opened 2022-05-25 08:34 UTC by dukcode

안녕하세요 Dan!

이번 PR에는 많은 내용 없이 요구사항 분석, E-R Diagram 설계, 및 Entity 구현만을 진행했습니다.

다음 PR에는 더 발전된 프로젝트로 올리겠습니다.

[요구사항 분석 및 , E-R Diagram Link](https://github.com/dukcode/airbnb/wiki/BE-%7C-데이터-베이스-설계)

앞으로 3주간 잘 부탁드립니다.!

2022-05-25 09:22 UTC, Hyune-c requested changes
수고하셨습니다. 

jpa 에 관련된 테스트를 많이 해보시면 좋을 것 같습니다.

2022-05-25 09:22 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    @GeneratedValue
@GeneratedValue의 strategy를 명시하는 것과 하지 않는 것에는 무슨 차이가 있을까요?

2022-05-25 09:22 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    private BookingStatus status;
👍

2022-05-25 09:22 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Image.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
Entity에서 `@RequiredArgsConstructor` 사용은 처음보는거 같아요. 혹시 어떤 의도인가요?
그리고 `@NoArgsConstructor`는 의도적으로 제거하신 건가요?

2022-05-25 09:22 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Location.java
> +@Embeddable
👍

2022-05-25 21:33 UTC, dukcode commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    @GeneratedValue
@GenerateValue의 strategy의 기본 값은 AUTO(DB의 기본생성전략을 따름)인데 h2의 기본 생성전략은 SEQUENCE, MySql의 기본 생성전략은 IDENTITY이므로 결국 배포시의 환경과 같이 맞추기 위해 IDENTITY로 명시적으로 적어주는게 맞을까요?

둘의 차이점에 대해 찾아봤는데 성능에 대한 이야기는 딱히 없어서요..

2022-05-26 01:35 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Booking.java
> +    @GeneratedValue
`MySql의 기본 생성전략은 IDENTITY`는 누가 정하고 있는지 알고 계신가요?

2022-05-26 01:53 UTC, Hyune-c approved these changes
리뷰 후 추가로 올라오는 커밋은 해당 PR에 있던 리뷰 내용을 보완하는 것을 목표로 해주세요.
지금처럼 초기 구현 외의 것을 또 올려주시면 PR의 덩어리가 점점 커집니다.

대화 거리가 많지만 본 PR의 범위를 벗어나는 것으로 간주하여 이번 PR은 approve 합니다.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/controller/HomeController.java
> +    }
`nit`
lombok을 활용할 수 있을 것 같아요.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    }
builder 패턴의 장단점을 고민하시고 다음 리뷰에 생각을 써주시면 좋을 것 같아요.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +    public static final double DIGIT = 10.0;
저는 이게 무슨 변수인지 잘 모르겠어요.
네이밍을 더 고려하는 방법도 있겠지만, 적절한 주석도 좋은 코딩의 일부라고 생각합니다.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +    }
이 메서드는 무슨 일을 하는건가요?
네이밍이 직관적이지 않고, 방의 전체 목록을 일단 조회하고 시작하는 것 부터가 일반적이진 않은 느낌이라고 생각해서 잘 이해가 안됩니다.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
> +                = restTemplate.getForObject(url, RoomChargeDistributionResponse.class);
Spring에서는 resttemplate보다 좋은 웹 레이어 테스트 방법을 지원해줄 것 같아요.
조금 더 찾아보시면 좋을 것 같습니다.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
> +    }
이 메서드의 설계에 대해 데이먼의 생각을 알려주세요.
저는 개선이 필요하다고 생각합니다.

2022-05-26 01:53 UTC, Hyune-c commented on BE/src/test/java/team21/airbnb/repository/RoomRepositoryTest.java
> +        assertThat(findRoom.getRoomCharge()).isEqualTo(roomCharge);
👍

2022-05-26 02:05 UTC, dukcode commented on BE/src/main/java/team21/airbnb/controller/HomeController.java
> +    }
@RequiredArgsConstructor 를 활용하겠습니다

2022-05-26 02:05 UTC, dukcode commented on BE/src/main/java/team21/airbnb/domain/Room.java
> +    }
충분한 공부 이후 생각을 작성해보도록 하겠습니다

2022-05-26 02:12 UTC, dukcode commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +    }
해당 메서드는
![image](https://user-images.githubusercontent.com/59705184/170400746-d8a76bfa-8a42-45ea-af62-08469b64dc18.png)

요금 버튼을 눌렀을 때 위 처럼 그래프를 구성할 수 있게
Room 가격에 따른 Room 갯수를 DIGIT 단위로 distribution하여 전달하는 메서드입니다.

2022-05-26 02:12 UTC, dukcode commented on BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
> +                = restTemplate.getForObject(url, RoomChargeDistributionResponse.class);
좋은 방법을 찾아보겠습니다.

2022-05-26 02:14 UTC, dukcode commented on BE/src/test/java/team21/airbnb/controller/HomeControllerTest.java
> +    }
Room 에 ceilRoomCharge() 메서드를 만들어 책임을 넘기는 게 더 적절하다고 생각하는데 Dan이 의도한 사항이 맞을까요?

2022-05-26 02:15 UTC, dukcode commented on BE/src/main/java/team21/airbnb/service/RoomService.java
> +    public static final double DIGIT = 10.0;
DISTRIBUTION_RANGE 가 더 적절한 이름 같습니다.!

2022-05-26 02:16 UTC, merged