[TEAM-07] BE Airbnb 1주차 1번째 PR Sally + zzangmin
codesquad-members-2022/airbnb pull request #48
Opened 2022-05-25 09:10 UTC by leezzangmin

안녕하세요 로치 !
리뷰해주셔서 감사합니다
PR 마감이 있는 것을 잊고 있다가 지금 보냅니다 . 죄송합니다.

* 진행상황

코드작성은 하지 않고 모델링에 집중했습니다.
springboot 프로젝트 기본설정만 진행했습니다.

![image](https://user-images.githubusercontent.com/64303390/170225952-26d02818-0c8c-45d1-9819-f445d583c1f9.png)

2022-05-25 14:12 UTC, tmdgusya commented
도식도 봤는데 깔끔하네요. 설계 그리신 부분도 깔금해서 알아보기 좋았어요.
이대로 개발해도 좋을것 같아요~ 유저 관련된 부분은 요구사항대로 일단 하드코딩으로 하시는거죠?

2022-05-25 14:12 UTC, tmdgusya requested changes
옵션만 꺼주세요~ 이거 키면 안좋은 옵션이라 꺼주셔야 합니다.

2022-05-25 14:12 UTC, tmdgusya commented on BE/airbnb/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
이 옵션은 Hibernate 에서 권장하지 않는 옵션이에요.
false 로 바꾸길 부탁드려요.

https://www.inflearn.com/questions/74167

2022-05-26 07:24 UTC, leezzangmin commented on BE/airbnb/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
생각없이 가져온 설정인데, 남겨주신 링크로 새로운 점 알아갑니다 감사합니다! ㅎㅎ

2022-05-26 15:06 UTC, merged

2022-05-26 15:07 UTC, tmdgusya commented
👍 
format_sql 은 일부러 끄신걸까요?