[Team-14 BE] airbnb 프로젝트 1주차 첫 번째 PR 입니다.
codesquad-members-2022/airbnb pull request #5
Opened 2022-05-25 07:07 UTC by naneun

## PR 인사

안녕하세요 brian team-14 에서 백엔드를 담당한 로니와 리아코입니다!
잘 부탁드리겠습니다~ 🙆‍♂️🙆‍♂️

## ERD
![tables drawio (3)](https://user-images.githubusercontent.com/47964708/170199760-04ef01c7-f126-4bd0-b080-c2a9c5c40ab0.png)

## 한 일
- [x] 요구사항 분석
- [x] 테이블 설계
- [x] API 설계 및 DTO 초안 작성
- [x] API 문서화 

## API 초안 목록

### Room
- [x]  숙소정보 상세 조회
- [x]  숙소목록 상세 조건으로 조회
- [x]  숙소목록 지역정보만으로 조회
- [x] 위시리스트에 속한 숙소 목록 조회

### Reservation
- [x] 숙소 예약하기
- [x] 숙소 예약 취소하기
- [x] 예약 상세 조회
- [x] 예약 리스트 조회

## 다음 PR 까지의 계획
- [ ] git action 을 사용하여 무중단 배포
- [ ] Elastic Search 학습
- [ ] 지도 API 학습

2022-05-25 16:55 UTC, wheejuni requested changes
수고하셨습니다 💯 
전반적으로 큰 무리가 없고요, 간단한 코멘트 몇 개 남겼습니다.

2022-05-25 16:55 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +@Getter
꼭 모든 필요에 `Getter` 필요하셨나요?

2022-05-25 16:55 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
`protected` 공개 수준 사용하신 이유 궁금합니다!

2022-05-25 16:55 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
> +    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
한 줄에 하나의 애노테이션만 기입합시다.

2022-05-25 16:55 UTC, wheejuni commented on backend/src/main/java/com/team14/cherrybnb/room/domain/Review.java
> +    private int starRating;
0.5점은 표현할 필요가 없으려나요?

2022-05-26 01:28 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +@Getter
아직은 필요하지 않지만!.. 다음부턴 Lombok 어노테이션을 사용하기 전에 한 번 더 고민해보도록 하겠습니다! 🤩

2022-05-26 01:33 UTC, naneun commented on backend/src/main/java/com/team14/cherrybnb/common/domain/Address.java
> +    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
네! 명심하겠습니다! 🤩

2022-05-26 01:36 UTC, CMSSKKK commented on backend/src/main/java/com/team14/cherrybnb/auth/domain/Member.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
JPA에서, DB의 정보로 엔티티를 생성할 때, 기본생성자와 reflection을 활용하기 때문에 꼭 필요한 것으로 알고 있습니다.

이 때 기본 생성자를 다른 곳에서의 사용을 막기위해서 `protected`로 했습니다.

2022-05-26 01:44 UTC, CMSSKKK commented on backend/src/main/java/com/team14/cherrybnb/room/domain/Review.java
> +    private int starRating;
사용자의 평점은 1 ~ 5점 정수로 남기는 것으로 생각했습니다. 

그리고 각 숙소의 평균 평점은 이후에 계산해서 소수점까지 표시할 예정입니다 😄

2022-05-27 02:35 UTC, merged