[Team14] 여행지 추천 및 자동 완성  검색 기능 구현
codesquad-members-2022/airbnb pull request #86
Opened 2022-05-27 05:15 UTC by asqw887

# 실행 결과 

https://user-images.githubusercontent.com/59790540/170632727-b5f52a17-865d-43f6-b98a-cd8f13098fc4.mp4

---

# 작업 목록 
- [x] (tuist) 테스트 타겟 앱 타겟에 의존하도록 dependencies 설정 
- [x] 추천여행지를 stub 객체 데이터로 보여주도록 구현 
- [x] 자동완성 기능을 담당할 UISearchController 생성 
- [x] MapKit에 제공하는 지역정보를 collectionView에 보여주도록 구현 
- [x] 달력 날짜를 나타내는 `Day`, 달력의 메타데이터를 표현하는 `MonthMetaData` 타입 생성
- [x] Calendar를 담당하는 ViewController가 DayCreator에게 요청하면 달력에 채울 날짜 객체를 받을 수 있도록 구현 (아직 ViewController 부분은 미구현)

---

# 고민과 해결 

- rootVC 에 있는 UISearchBar를 UISearchController 로 변경하려는 시도를 했으나, 다음 화면과 레이아웃이 달라 매번 ViewWillAppear, ViewWillDisappear 를 설정해주어야 하는 문제가 있고 전환이 잘 실행되지 않음 
 -> rootVC에 있는 searchBar는 단순히 다음 VC로 넘어가는 액션만 필요하기 때문에 변경하지 않고 UISearchBar를 터치하면 다음 VC를 push해주고, 다음 VC에서 UISearchController를 활용하는 방식으로 구현 

- searchBar에 텍스트를 입력했을 때와, 그렇지 않을 때 CollectionView에 필요한 DataSource를 어떻게 바꿔주어야할지 고민
-> bool 값으로 분기처리를 해주어 상태에 따라 필요한 DataSource를 보여주도록 처리함.

2022-05-27 22:47 UTC, GangWoon requested changes
안녕하세요.
이번 리뷰를 진행하면서 모델쪽 코드를 읽을때, 제 기준에선 의미를 분류하는 기준이 어색하다는 느낌을 많이 받았습니다.
또한 하나의 프로젝트에서 여러 사람이 작성하고 있다는 느낌도 받았습니다.
회사마다 다르지만, 한 배를 타고 있는 느낌을 좋아하는 회사도 존재하며, 저 또한 프로젝트를 관리하는 입장에서 일관성을 높게 생각하고 있습니다.

모델에 관한 코맨트가 만약 이해하기 어려우시다면 오늘 시간을 맞출수 있다면 서로 의견을 나누는 자리를 만들어도 괜찮아 보입니다

2022-05-27 22:47 UTC, GangWoon commented on iOS/Plugins/Cherrybnb/Sources/tuist-my-cli/main.swift
> +print("Hello, from your Tuist Task")
불필요한 코드처럼 보입니다.

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +            print(CalendarError.offsetMonthGeneration)
에러 핸들링 하실때 프린트문이 사용자에게도 도움이 될까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
> +    }
통일성이 없는 부분 같습니다.
다른 셀은 메소드로 업데이트 하셨거든요.

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
> +    func setLayout() {
외부로 노출할 이유가 있을까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/View/LocationCell.swift
> +    }
뷰를 꾸미는 코드도 상이한거 같습니다.

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/ViewController/ListCollectionViewController.swift
> +            self.recommendationData += place
문제가 발생할거 같은데 어떤문제일까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/Day.swift
> +    }()
모델에서 포매터를 알고 있을 이유가 있을까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/Day.swift
> +
모델에 꼭 필요한 속성일까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/Day.swift
> +    let date: Date
데이와 큰 차이가 없는 구조체로 보입니다.
구조체로 의미를 나누는 방법만 존재했을까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +    var selectedDate: Date?
날짜를 만드는공간에서 선택된 날짜가 의미가 있을까요?
캘린더를 생성하고 관리하는 공간에서 의미가 있는 데이터처럼 보입니다.

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +    }
해당 파일 이외에서 사용될 메소드들인가요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +struct MonthCreator {
날짜를 생성하는 객체와 의미적으로 많이 다를까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/Model/MonthMetaData.swift
> +}
먼스라는 구조체에 포함하지 않는 이유가 있을까요?

2022-05-27 22:47 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/ViewController/CalendarPickerViewController.swift
> +    private let didEndDateChanged: ((Date) -> Void)? = nil
현재 상태에서 의미가 있는 코드인가요?

2022-05-30 02:32 UTC, asqw887 commented on iOS/Targets/Cherrybnb/Sources/Search/ViewController/ListCollectionViewController.swift
> +            self.recommendationData += place
요청할때마다 배열에 데이터가 계속해서 쌓이겠네요. 수정하겠습니다.

2022-05-30 03:04 UTC, asqw887 commented on iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
> +    func setLayout() {
내부에서만 사용하는 함수라 Private로 지정해주었습니다.

2022-05-30 08:33 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/Model/MonthMetaData.swift
> +}
생각해보니 Month 안에 포함되도록 하는 게 더 자연스럽네요. 수정했습니다.

2022-05-30 08:33 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/ViewController/CalendarPickerViewController.swift
> +    private let didEndDateChanged: ((Date) -> Void)? = nil
생성자를 통해서 클로저 주입해줄 수 있도록 수정했습니다!

2022-05-30 08:34 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +struct MonthCreator {
Day가 Month 안에 속하도록 구조를 변경해 `MonthCreator`는 삭제하였습니다.

2022-05-30 08:34 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +    }
범용적으로 사용될 수 있는 메서드들이라고 생각이 들어서 Common에 따로 정리해두었습니다.

2022-05-30 08:35 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/Model/DayCreator.swift
> +    var selectedDate: Date?
이 부분은 Selection 로직을 미리 생각해서 넣어두었던 것인데, 일단 Selection 로직을 구현하고 나서 개선해보도록 하겠습니다!

2022-05-30 08:35 UTC, BumgeunSong commented on iOS/Targets/Cherrybnb/Sources/Search/View/LocationCell.swift
> +    }
체즈와 상의해서 뷰 코드의 구조를 일관성있게 통일했습니다!

2022-05-30 08:59 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/ViewController/ListCollectionViewController.swift
> +            self.recommendationData += place
작성하신 코드가 어떤 상황인지에 대해서 구체적으로 설명해주실 수 있을까요

2022-05-30 13:52 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search/View/CalendarPickerCollectionViewCell.swift
> +    var day: Day?
동일한 문제인거 같습니다.
외부로 노출하는 이유가 있을까요?

2022-05-30 13:53 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
> +    private let didDataRangeSelect: ((Range<Date>) -> Void)?
위 코드를 언급드렸던 이유는, 현재 CalendarPickerViewController에서 사용하지 않는 코드이기에 말씀드렸던 부분이였습니다.

2022-05-30 13:53 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
> +        contentView.addSubview(numberLabel)
동일한 코드를 작성하신 이유가 있을까요?

2022-05-30 13:59 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Support/AppDelegate.swift
> +        let viewController = try? CalendarPickerViewController(basedate: .init(), numOfMonths: 10, didDateSelect: nil, didDataRangeSelect: nil)
에러 핸들링을 신경쓰기 시작하신 모습은 정말 좋은 거 같습니다.

다만
뷰컨트롤러를 생성할때 실패할 수 있는 걸까요?
날짜 생성기를 생성할때 실패할 수 있는 걸까요?
날짜 생성기가 날짜를 생성할 때 실패할 수 있는걸까요?

지금 에러 핸들링을 시작하시면서 최상단의 모습이 개인적인 생각으로 어색한 부분 같습니다.
뷰컨트롤러를 생성하는데 왜 실패할 수 있는거지 라는 생각들었습니다.
현재 문제가 발생하는 장소를 명확하게 분리하시면 읽는 사람에게 혼돈을 줄여주는 코드가 될 거 같습니다.

2022-05-30 14:03 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search_Date/Model/Month.swift
> +        let isPast: Bool?
옵셔널을 사용하는 안좋은 습관 중 하나일 거 같습니다.
최근에 동료분과 나눴던 주제이기도 하며, 적절한 사용법에 대해서 좋은 주제일 거 같습니다.

위 처럼 Day라는 컨테이너의 date속성은 없을 경우에 의미가 있는 구조체인가라는 생각이 듭니다.
추가적으로 왜 모든 프로퍼티를 옵셔널로 생성하신건지 의문이 들고요.
이런 코드가 늘어나게 되면, 초기화 시킬때 어떤 프로퍼티를 할당해줘야하는지 설계를 한 사람도 햇갈리기 시작할 겁니다.
그렇다고 모든 옵셔널 프로퍼티를 막자라는 뜻은 아닙니다.

위에서 제가 잠깐 언급드린대로  Day와 Date는 땔래야 떌 수 없는 관계인데 이걸 Optional로 선언하신 부분이 너무나도 어색했습니다.
위처럼 작성하신 이유가 궁금하네요. 설명해주시겠나요?

2022-05-30 14:04 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search_Date/View/CalendarPickerViewCell.swift
> +    }
셀 재사용 부분을 신경써주신 부분은 인상깊네요 :)

2022-05-30 14:05 UTC, GangWoon commented on iOS/Targets/Cherrybnb/Sources/Search_Date/Controller/CalendarPickerViewController.swift
> +        self.calendarPicker = try CalendarPicker(basedate: basedate, numOfMonths: numOfMonths)
카멜 케이스로 통일하셨던 거 같은데 해당 부분은 무시한거 같습니다.

2022-05-31 04:06 UTC, merged