[Team - 06][BE] 에어비앤비 프로젝트 1주차 2회차 PR
codesquad-members-2022/airbnb pull request #88
Opened 2022-05-27 05:19 UTC by zbqmgldjfh

## 안녕하세요 Dion! 
우선 저희 팀의 리뷰를 담당해 주셔서 감사의 인사를 전합니다!!

이번 2차 PR을 진행하면서 한가지 고민거리가 있었는데... 이에 대하여 답변해주시면 감사하겠습니다 ㅠ,ㅠ

### 1. Native Query 질문

다음 두 메서드 searchByCondition 과 searchByConditionQueryDsl 은 동일한 일을 수행하고 있습니다.

```java
@Override
public List<House> searchByCondition(Point position, Integer minFee, Integer maxFee) {
  double baseLatitude = position.getX();
  double baseLongitude = position.getY();
  double distance = 1000; // m 단위

  // TODO : *를 필드 명으로 변경해주기
  Query query = em.createNativeQuery("" +
                                     "SELECT * \n" +
                                     "FROM house AS h \n" +
                                     "WHERE (ST_Distance_Sphere(h.point, point(?1, ?2)) < ?3) AND h.price >= ?4 AND h.price <= ?5"
                                     , House.class);

  query.setParameter(1, baseLatitude);
  query.setParameter(2, baseLongitude);
  query.setParameter(3, distance);
  query.setParameter(4, minFee);
  query.setParameter(5, maxFee);

  return query.getResultList();
}
```

다음은 queryDsl 을 통해 조건을 동적으로 받고 싶어 만들어본 함수 입니다.

다만 queryDsl에서 mysql의 함수를 직접 이용하려다 보니 간단하게 사용할수가 없었습니다...

```j
@Override
public List<House> searchByConditionQueryDsl(Point position, Integer minFee, Integer maxFee) {
double baseLatitude = position.getX(); // 내 위치 y
double baseLongitude = position.getY(); // 내 위치 x
double distance = 1000; // m 단위

QHouse subHouse = new QHouse("subHouse");

List<House> results = queryFactory
                                                .selectFrom(house)
                                                .where(
                                                                Expressions.stringTemplate(
                                                                "function('ST_Distance_Sphere', {0}, {1})", 
                                                                subHouse.point, GeometryUtils.toPoint(baseLatitude, baseLongitude))
                                                                .as("subDistance")
                                                                .loe(String.valueOf(distance)
                                                            )
                                                 ).fetch();

     return results;
}
```

루시드와 거의 5/26일 하루를 바쳤지만.... queryDsl 상에서 mysql의 함수 사용이 잘 작동하지 않았습니다...

여러 글들을 읽어보니 Expressions.stringTemplate를 사용하라고 하던데.... 인자가 잘 전달되지 않는것 같습니다..

이부분 해결책을 알려주신다면 감사하겠습니다...

    
### 2. nativeQuery에서의 컬럼 명시
native Query를 통해 쿼리 작성 시 전체 컬럼 조회(*) 방식을 지양하고자 했는데, 임베디드 타입의 경우에도 하나 하나 컬럼을 찍어야 하는 불편함이 생겼습니다.

예를 들면 다음과 같습니다.

```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "house_id")
private Long id;

private String name;
private int price;

@Embedded
private DetailInfo detailInfo;
```

이처럼 Embedded type인 DetailInfo를 가져올 때, DetailInfo 내부에 들어있는 모든 컬럼을 직접 작성해 줘야 합니다. 
반드시 모든 컬럼이 필요한 경우에는 예외적으로 “*”를 작성해도 괜찮을까요?

2022-05-27 12:06 UTC, ksundong requested changes
안녕하세요.  Shine & Lucid 리뷰어 dion입니다.

1. `Native Query`가 반드시 필요한 상황인가요?  어쩌면 두분이 쓰시기에 JPA는 아직  배울점이 많은 도구는 아닐까요? 또한 QueryDSL 도입 역시 굳이 필요해보이진 않는 것 같습니다. 제가 단순히 해결책만 알려드린다고 해결이 가능한 것이 아니라, 스스로 트러블 슈팅이 가능하신 툴을 선택해 사용하시는걸 추천드립니다.
2. 네. 예외는 없습니다. 특히 객체에 매핑하는 코드는 반드시 해주세요. 또, Native Query를 작성해야 할 때, 내가 정말 맞는 판단을 하고 있는 건지, 간단한 방법은 정말 없는지, 그래도 안된다면 JPA가 과연 내가 짜려하는 애플리케이션에 적합한 도구인지 생각해보세요.

1주차가 다 끝났네요. 고생하셨습니다.
아쉬운 부분이 곳곳에 눈에 띄어서 변경요청드립니다.
고생많으셨습니다~

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/api/houses/dto/ImageResponse.java
> +    }
`setter` 가 필요한 이유가 있었나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/api/houses/dto/SearchConditionRequest.java
> +    private LocalDateTime endDate;
타입과 일치하지 않는 네이밍인 이유가 있나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/api/houses/SearchController.java
> +public class SearchController {
아직도 `SearchController` 인 이유가 있나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/domain/House.java
>      private List<WishList> wishLists = new ArrayList<>();
여긴 안바뀌었네요. 정말 역참조 할 일이 있나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/domain/Location.java
> +    }
이 클래스는 무엇을 위한 클래스인가요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/domain/Role.java
> +    GUEST, HOST, ADMIN
이렇게 변경하는건 매우 위험한 선택입니다.
현업에서는 마이그레이션 쿼리와 함께 변경합니다.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/domain/User.java
> +    private List<House> hostedHouse;
`houses` 가 더 맞지 않을까요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +    private final EntityManager em;
`EntityManager` 를 직접 사용할 일이 있나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        // TODO : *를 필드 명으로 변경해주기
네 이건 꼭 해주세요.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
굳이 NativeQuery가 필요한가 싶네요. JPA에서 추가 모듈로 공간데이터를 사용하는 기능은 제공할텐데 사용은 해보셨나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
만약에 사용하기 어렵다면, 이 기술이 우리팀에게 정말 최선인지도 고민해보시기 바랍니다.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/service/HouseService.java
> +    public List<House> findByCondition(Point point, Integer minFee, Integer maxFee) {
항상 비즈니스 로직 작성시에 트랜잭션은 필요하진 않은지 생각해보시길 바랍니다.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/api/houses/SearchController.java
> +}
가급적이면 `Controller` 에 도메인이 등장하지 않도록 해주세요.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +public class GeometryUtils {
해당 코드에 주석이라도 좀 달아주는게 어떨까요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +    public static Location calculateByDirection(Double baseLatitude, Double baseLongitude, double distance,
무엇을 계산하기 위한 메서드인가요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +        Double distanceRadius = distance / 6371.01;
6371.01 은 어떤 수인가요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +        }
이런 예외처리는 제발 하지 말아주세요.

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/resources/application.yml
> +    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
왜 5.6 버전에 대응하는 Dialect를 사용하게 되었나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +@SpringBootTest
스프링 없이는 테스트할 수 없었나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +        nowPosition = (Point) new WKTReader().read(pointWKT);
그냥 Point 타입을 직접 만들어줄 수는 없었나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +
`saveAll` 이라는 것도 있습니다.

2022-05-27 12:06 UTC, ksundong commented on BE/src/test/resources/application.yml
> +#  org.hibernate.SQL: debug
왜 안 지우고 주석처리 해주셨나요?

2022-05-27 12:06 UTC, ksundong commented on BE/src/main/resources/application.yml
>      properties:
jpa의 open-in-view에 대해서도 학습해보시길 바랍니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/api/houses/dto/ImageResponse.java
> +    }
DTO에 setter가 있어도 무방하다 생각하여 사용하게 되었는데,
필요한 시점에만 사용하도록 하겠습니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/api/houses/dto/SearchConditionRequest.java
> +    private LocalDateTime endDate;
타입과 일치하도록 변수명을 변경하였습니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/api/houses/SearchController.java
> +public class SearchController {
아 함수의 이름까지 변경해야 한다는 인식을 못한것 같습니다. 함수 명도 HouseController 로 변경하였습니다.

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/test/resources/application.yml
> +#  org.hibernate.SQL: debug
주석 처리는 지우도록 하겠습니다!

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/domain/House.java
>      private List<WishList> wishLists = new ArrayList<>();
역참조가 생각해보니 House에서는 필요없는것 같습니다. 사용자만 찜목록에 접근하면 될것 같습니다.
수정하도록 하겠습니다.

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +
service에서 현재 테스트를 위해 saveAll을 만들 필요는 없을 것 같아서, Repository test 시 고려하도록 하겠습니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/domain/Location.java
> +    }
더이상 필요없는 도메인이라 제거하도록 하겠습니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/domain/Role.java
> +    GUEST, HOST, ADMIN
테이블 변경에 대한 주의를 하도록 하겠습니다.

2022-05-29 07:43 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/domain/User.java
> +    private List<House> hostedHouse;
아!! 변수명 변경하도록 하겠습니다!!

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/main/resources/application.yml
> +    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
참조한 자료들에서 MySQL 공간 데이터 타입을 사용하기 위해 해당 버전을 사용하라고 되어있었습니다! MySQL 8.0 이상에서도 해당 기능을 사용하기 위해서는 5.6버전의 Dialect만을 사용해야 하는 걸로 이해했습니다.

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +        }
새로운 예외 생성 또는 log 출력등의 방식으로 의미있는 예외 처리를 하도록 하겠습니다!

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/main/java/com/airbnb/api/houses/SearchController.java
> +}
서비스계층까지만 도메인을 사용하도록 하겠습니다.

2022-05-29 07:43 UTC, leejohy-0223 commented on BE/src/main/java/com/airbnb/service/HouseService.java
> +    public List<House> findByCondition(Point point, Integer minFee, Integer maxFee) {
용도에 맞게 트랜잭션을 적용하도록 하겠습니다.

2022-05-29 07:49 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +    private final EntityManager em;
MySQL의 ST_Distance_Sphere 를 직접 사용해보고 싶어 NativeQuery 작성용으로 사용하게 되었습니다.

2022-05-29 07:49 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        // TODO : *를 필드 명으로 변경해주기
변경 완료 하였습니다!!

2022-05-29 07:50 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
MySQL의 ST_Distance_Sphere 를 직접 사용해보고 싶어 사용하게 되었습니다.
호눅스가 수업중에서도 사용해보란 말을 해주셔서 MySQL의 함수를 사용하보려 하고 있습니다.

2022-05-29 07:51 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
해당 기술이 우리팀에 최선인가? 음.... 어려운 질문인것 같습니다... 최선인지를 확인하려면 기준이 필요할탠데,
판단의 기준이라.... 음...

2022-05-29 07:52 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +    public static Location calculateByDirection(Double baseLatitude, Double baseLongitude, double distance,
초기에는 MySQL의 MBRcontains를 사용하려 했기 때문에 만들었는데 더이상 사용하지 않아 제거하였습니다.

2022-05-29 07:53 UTC, zbqmgldjfh commented on BE/src/main/java/com/airbnb/utils/GeometryUtils.java
> +        Double distanceRadius = distance / 6371.01;
평균 지구 반경에 해당되는 거리 입니다!! 하지만 더이상 사용하지 않아 삭제하였습니다.

https://detegice.github.io/%EA%B8%B0%ED%95%98-%EB%8C%80%EA%B6%8C%EA%B1%B0%EB%A6%AC/

2022-05-29 07:54 UTC, zbqmgldjfh commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +@SpringBootTest
MySQL의 함수를 끌어다 사용하기 때문에 Slice test가 어려운것 같습니다.

2022-05-29 07:55 UTC, zbqmgldjfh commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +        nowPosition = (Point) new WKTReader().read(pointWKT);
음 충분히 적용 가능한 리뷰라 생각합니다만, 이번 프로젝트 에서는 Point를 가져다 사용하기로 하였습니다 ㅠ,ㅠ

2022-05-29 15:11 UTC, ksundong commented on BE/src/main/java/com/airbnb/api/houses/SearchController.java
> +public class SearchController {
클래스명을 잘못 말씀하신거겠죵?

2022-05-29 15:11 UTC, ksundong commented on BE/src/main/java/com/airbnb/domain/Role.java
> +    GUEST, HOST, ADMIN
네 보통 개발하는 환경에서도 배포가 이미 되었다면 배포된 순간부터 신경써야 한다고 생각합니다.

2022-05-29 15:13 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
네 분명 사용을 위한 학습도 필요하다고 생각하긴 합니다만, 그것이 개발진척을 한 이후에 고민해도 늦지 않겠다는 생각도 드네요.

2022-05-29 15:14 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
최선인지 판단하는 기준은 "'우리 팀'이 '제한된 기간'동안 '요구사항을 충족'할 수 있는가"가 아닐까요?

2022-05-29 15:15 UTC, ksundong commented on BE/src/main/resources/application.yml
> +    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
8.0에 해당하는 Dialect는 공간데이터를 지원하지 않나용?

2022-05-29 15:16 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +@SpringBootTest
`Service`에서 `MySQL`을 알아야한다면, 뭔가 잘못된건 아닐까요?

2022-05-29 15:16 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +        nowPosition = (Point) new WKTReader().read(pointWKT);
`Point`는 생성자나 정적 팩토리 메서드가 포함되어있지 않나요?

2022-05-29 15:16 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +
기본적으로 제공되는 메서드입니다.

2022-05-29 15:17 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +
무엇을 테스트 해야하는지 특정을 해보시면 좋을 것 같네요.
서비스 영역은 무엇을 표현하기 위한 계층이며, 무엇을 테스트해야하나요?

2022-05-29 15:24 UTC, ksundong approved these changes
고생하셨습니다. 이번주도 화이팅하세요~~

2022-05-29 15:24 UTC, ksundong commented on .github/workflows/main.yml
> +          aws-region: ${{ secrets.AWS_REGION }}
👍

2022-05-29 15:24 UTC, ksundong commented on .github/workflows/main.yml
> +# airbnb-deploy.yml
Github Actions를 사용해주셨군용!

2022-05-29 15:24 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +    private final EntityManager em;
아하 `entityManger`를 사용하고 있었군요. 왜 못봤을까요~~..

2022-05-29 15:24 UTC, ksundong commented on BE/src/main/java/com/airbnb/repository/HouseCustomRepositoryImpl.java
> +        Query query = em.createNativeQuery("" +
JPA는 조회성 쿼리에는 약간의 약점이 있어서, 다른 기술을 섞어쓰기도 합니다.
참고가 되셨으면 좋겠네요.

2022-05-29 15:24 UTC, merged

2022-05-30 02:14 UTC, leejohy-0223 commented on BE/src/main/resources/application.yml
> +    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
다시 찾아보니 org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect로 변경 가능했습니다! ㅎㅎㅎ 감사합니다.

2022-05-30 02:18 UTC, leejohy-0223 commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +        nowPosition = (Point) new WKTReader().read(pointWKT);
org.locationtech.jts.geom.Point에는 생성자나 정적 팩토리 메서드가 없어서 위와 같은 방식으로 변환할 수 있다고 참고하였습니다!

2022-05-30 02:23 UTC, leejohy-0223 commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +
생각해보니 해당 부분은 Repository에서 작성되어야 할 테스트로 생각됩니다. 
서비스 영역은 비즈니스적 의미를 갖는 로직을 담는다고 우선 생각이 되며, 테스트 시 repository를 Mocking해서 진행해야할 것 같습니다.

2022-05-30 04:28 UTC, zbqmgldjfh commented
Dion 혹시 그 질문 1번에 대해서 조금 더 알려주실수 있나요? ST_Distance_Spher을 QueryDSL 상에서 쓰고 싶은데...
아직도 방법을 못찾았습니다..... 조금의 힌트라도 ㅠ,ㅠ

2022-05-30 16:00 UTC, ksundong commented on BE/src/test/java/com/airbnb/service/HouseServiceTest.java
> +        nowPosition = (Point) new WKTReader().read(pointWKT);
오잉 그랬군요. 예전에 같은 클래스를 썼던 것 같은데 잘 기억이 안나는군요.